<!DOCTYPE html>
<html lang="en"><head>
<script src="L6-beyond-pcs_files/libs/clipboard/clipboard.min.js"></script>
<script src="L6-beyond-pcs_files/libs/quarto-html/tabby.min.js"></script>
<script src="L6-beyond-pcs_files/libs/quarto-html/popper.min.js"></script>
<script src="L6-beyond-pcs_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="L6-beyond-pcs_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="L6-beyond-pcs_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="L6-beyond-pcs_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Hae Kyung Im, PhD">
  <meta name="dcterms.date" content="2026-04-08">
  <title>Beyond PCs: Mixed Effects Models &amp; LD Score Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="L6-beyond-pcs_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="L6-beyond-pcs_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="L6-beyond-pcs_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="../custom.css">
  <link href="L6-beyond-pcs_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="L6-beyond-pcs_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="L6-beyond-pcs_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="L6-beyond-pcs_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Beyond PCs: Mixed Effects Models &amp; LD Score Regression</h1>
  <p class="subtitle">BIOS 25328 · Lecture 6</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Hae Kyung Im, PhD 
</div>
</div>
</div>

  <p class="date">2026-04-08</p>
</section>
<section id="last-weeks-recap" class="slide level2">
<h2>Last week’s recap</h2>
<p>We showed that population structure <strong>inflates GWAS test statistics</strong> — and PCs fix it</p>
<ul>
<li>The HapMap growth phenotype differed by population → J-shaped p-value histogram</li>
<li>Adding the top 4 PCs as covariates → uniform p-value distribution, inflation gone</li>
<li>PCs are the most common correction in practice</li>
</ul>
<p>But two questions remain:</p>
<ol type="1">
<li><strong>PCs don’t handle everything</strong> — cryptic relatedness and family structure require a more principled model</li>
<li><strong>Inflated λ doesn’t always mean bias</strong> — in large studies λ &gt; 1 can reflect true polygenicity, not confounding</li>
</ol>
<aside class="notes">
<p>Last week we saw a striking example of what can go wrong in GWAS when samples come from different populations. The HapMap growth phenotype was different on average across populations, so when we ran GWAS naively, we got a J-shaped p-value histogram — far too many small p-values. Adding just four principal components as covariates fixed the problem: the histogram went back to the flat uniform shape we expect under the null.</p>
<p>But this raises two important questions we didn’t fully answer. First: PCs work well for broad ancestry differences, but what about cases where individuals are related to each other — like siblings, cousins, or even distant relatives in a biobank? PCs don’t fully capture that. Second: when we see λ &gt; 1, is it always bad? In very large studies with polygenic traits, most variants really do have tiny effects, and that can also inflate test statistics. So a blanket correction like dividing everything by λ might actually throw away real signal.</p>
<p>Those two questions motivate everything in today’s lecture.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<ol type="1">
<li>Understand <strong>genomic control</strong> (λ inflation factor)</li>
<li>Build intuition for the <strong>mixed effects model</strong> (GRM as random effect) — answers question 1</li>
<li>Understand the <strong>kinship/GRM</strong> as a random effect covariance structure</li>
</ol>
<div class="fragment">
<p>Time permitting</p>
<ol start="4" type="1">
<li>Learn how <strong>LD score regression</strong> separates true polygenicity from confounding — answers question 2</li>
<li>Interpret <strong>genetic correlation</strong> estimates from LD score regression</li>
</ol>
<aside class="notes">
<p>We have five goals today. The first three are core: understanding how genomic control works, building intuition for the mixed effects model, and understanding what the kinship/GRM matrix actually represents.</p>
<p>The last two — LD score regression and genetic correlation — are the payoff of the lecture if we have time. LD score regression is one of the most widely used tools in modern human genetics, so it’s worth the investment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="genomic-control-devlin-roeder-1999" class="slide level2">
<h2>1. Genomic Control (Devlin &amp; Roeder, 1999)</h2>
<ul>
<li><strong>Assumption</strong>: effects of population stratification and cryptic relatedness are <strong>constant across the genome</strong></li>
<li>Test statistics are distributed <span class="math inline">\(\lambda \times \chi^2\)</span></li>
<li>Estimate <span class="math inline">\(\lambda\)</span> using:
<ul>
<li>Mean of test statistics, or</li>
<li>Median: <span class="math inline">\(\lambda = \text{median}(\chi^2) / 0.4549\)</span></li>
</ul></li>
<li><span class="math inline">\(\lambda &lt; 1.05\)</span> considered acceptable inflation</li>
</ul>
<aside class="notes">
<p>Genomic control is one of the earliest and simplest corrections for population stratification. The key assumption is that whatever is inflating test statistics — ancestry differences, cryptic relatedness — it inflates them all by roughly the same amount, uniformly across the genome.</p>
<p>If that’s true, we can estimate a single inflation factor λ and divide all our test statistics by it. We estimate λ from the median of the chi-squared distribution rather than the mean, because the median is more robust — a handful of truly associated SNPs with large statistics could pull the mean up without reflecting real confounding.</p>
<p>The rule of thumb is λ &lt; 1.05 is acceptable. This is still widely used as a quick sanity check even when more sophisticated methods are applied.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-of-a-nice-gwas-qq-plot" class="slide level2">
<h2>Example of a Nice GWAS QQ-Plot</h2>

<img data-src="images/_page_6_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>A QQ-plot compares the distribution of p-values we observe against what we’d expect if no SNP had any association with the trait. Under the null hypothesis, p-values should be uniformly distributed — so the QQ-plot should follow the diagonal line.</p>
<p>In a well-controlled GWAS, most points sit on the diagonal (no inflation), and only a few points — the true hits — peel off at the top. That’s exactly what a good GWAS looks like. Although, this reasoning needs to be updated given current sample sizes — with hundreds of thousands of samples, even a truly polygenic trait will show a lifted QQ-plot that doesn’t indicate confounding. That’s the subject of the LDSC section.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genomic-control-adjustment" class="slide level2">
<h2>Genomic Control Adjustment</h2>

<img data-src="images/_page_7_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>This is a deliberately extreme example: all the cases come from one population, all the controls from another. This creates massive inflation. Every SNP that differs in frequency between the populations looks associated, even though none of them are truly causal for the trait.</p>
<p>After applying genomic control — dividing every chi-squared statistic by λ — the inflation is corrected. The key point is that this correction is blunt: it treats every SNP the same, whether the inflation is due to stratification or due to real signal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="mixed-effects-models" class="title-slide slide level1 center">
<h1>Mixed Effects Models</h1>

</section>
<section id="recall-the-regression-approach-to-gwas" class="slide level2">
<h2>Recall the Regression Approach to GWAS</h2>
<p><span class="math display">\[Y = X\beta + \epsilon\]</span></p>
<ul>
<li><span class="math inline">\(\beta\)</span> = <strong>fixed</strong> effect (SNP effect of interest)</li>
<li><span class="math inline">\(X\)</span> = genotype matrix (SNP dosages)</li>
</ul>
<p>Works well when individuals are unrelated and ancestry is homogeneous</p>
<aside class="notes">
<p>Before introducing mixed effects models, let’s remind ourselves of what we already know. Standard GWAS uses simple linear regression: we regress the phenotype Y on genotype X for each SNP. The coefficient β tells us how much the phenotype changes per copy of the effect allele.</p>
<p>This works well when individuals are independent and ancestry is homogeneous. But when some individuals are related, their phenotypes are correlated for reasons beyond the SNP being tested — and that correlation violates the independence assumption of ordinary regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="extending-the-regression-model-with-a-random-effect" class="slide level2">
<h2>Extending the Regression Model with a Random Effect</h2>
<!-- #### Kang et al. — Variance Component Model (EMMAX) -->
<p><span class="math display">\[Y = X\beta + u + \epsilon\]</span></p>
<p><span class="math display">\[u \sim N(0,\, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<ul>
<li><span class="math inline">\(\beta\)</span> = <strong>fixed</strong> effect (SNP effect of interest)</li>
<li><span class="math inline">\(u\)</span> = <strong>random</strong> effect (captures population/family structure)</li>
<li><span class="math inline">\(\mathbf{K}\)</span> = genetic relatedness matrix (GRM)</li>
</ul>
<p>Useful to adjust for confounding due to <strong>population structure</strong>, <strong>family structure</strong>, and <strong>cryptic relatedness</strong></p>
<div class="source-credit">
<p>Kang et al.&nbsp;<em>Variance component model to account for sample structure in genome-wide association studies.</em> Nature Genetics, 2010.</p>
</div>
<aside class="notes">
<p>The mixed effects model adds one new term to the regression: a random effect u. Think of u as a “background genetic similarity” term that absorbs the phenotypic correlation due to shared ancestry or relatedness.</p>
<p>The key insight: we don’t estimate u for each individual directly. Instead, we describe its distribution. We say u behaves like a draw from a normal distribution whose variance is shaped by a matrix K — the genetic relatedness matrix. When two individuals are genetically similar, their u values are also expected to be similar. That’s what K encodes.</p>
<p>The word “mixed” in mixed effects model refers to having both fixed effects (β, the SNP we’re testing) and random effects (u, the background structure).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-vectors" class="slide level2">
<h2>Example with 4 Individuals — Vectors</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vectors for 4 individuals:</p>
<p><span class="math display">\[\begin{bmatrix} y_1 \\ y_2 \\ y_3 \\ y_4 \end{bmatrix} = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{bmatrix} \cdot \beta + \begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \end{bmatrix} + \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \epsilon_3 \\ \epsilon_4 \end{bmatrix}\]</span></p>
<p><span class="math display">\[Y \sim N(X\beta,\; \sigma_g^2 \cdot \mathbf{K} + \sigma_e^2 \cdot \mathbf{I})\]</span></p>
<aside class="notes">
<p>Let’s make this concrete with just 4 individuals: 2 from AFR ancestry, 2 from EUR ancestry. We can write out all four components of the model as vectors.</p>
<p>The phenotype vector Y has four entries. The fixed part Xβ — the SNP effect — is a scalar β times the vector of genotypes. The random effect u is a vector of four numbers, one per individual. The residual ε is also a vector of four numbers.</p>
<p>The key result is the distribution of Y overall: it’s a multivariate normal with mean Xβ and variance that’s a combination of the genetic structure (σ²g · K) and the residual noise (σ²e · I). This is the equation that the EMMAX software, one implementation of the mixed effects model, fits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-random-effect-u" class="slide level2">
<h2>Example with 4 Individuals — Random Effect <em>u</em></h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vector <span class="math inline">\(u\)</span> and its variance matrix:</p>
<p><span class="math display">\[\begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \end{bmatrix} \sim N \left( \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix},\; \sigma_g^2 \cdot \begin{bmatrix} k_{11} &amp; k_{12} &amp; k_{13} &amp; k_{14} \\ k_{21} &amp; k_{22} &amp; k_{23} &amp; k_{24} \\ k_{31} &amp; k_{32} &amp; k_{33} &amp; k_{34} \\ k_{41} &amp; k_{42} &amp; k_{43} &amp; k_{44} \end{bmatrix} \right)\]</span></p>
<p><span class="math inline">\(u\)</span> is a multivariate normal random variable</p>
<aside class="notes">
<p>The random effect u is a vector drawn from a multivariate normal distribution. The mean is zero — we’re not saying individuals from one population have higher phenotypes, just that their u values are correlated with each other.</p>
<p>The variance matrix is σ²g · K. Think of K as a “similarity map” between individuals. If individual 1 and individual 2 are from the same population, their u values are expected to covary — they have similar genetic backgrounds, so they’ll tend to have similar background effects on phenotype.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-residual-ε" class="slide level2">
<h2>Example with 4 Individuals — Residual <em>ε</em></h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vector <span class="math inline">\(\epsilon\)</span> and its variance matrix:</p>
<p><span class="math display">\[\begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \epsilon_3 \\ \epsilon_4 \end{bmatrix} \sim N \left( \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix},\; \sigma_e^2 \cdot \begin{bmatrix} 1 &amp; 0 &amp; 0 &amp; 0 \\ 0 &amp; 1 &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; 1 &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; 1 \end{bmatrix} \right)\]</span></p>
<p><span class="math inline">\(\epsilon\)</span> is a multivariate normal random variable</p>
<aside class="notes">
<p>The residual ε captures everything the model doesn’t explain — environmental noise, measurement error, and any genetic effects not captured by K. We assume these residuals are independent across individuals: knowing that individual 1’s residual is large tells us nothing about individual 2’s.</p>
<p>That’s why the variance of ε is σ²e · I — the identity matrix, all ones on the diagonal, all zeros off-diagonal. This is the same independence assumption as ordinary regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="checkpoint-what-is-the-distribution-of-y" class="slide level2">
<h2>Checkpoint: What is the Distribution of Y?</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon\]</span></p>
<p><span class="math display">\[u \sim N(0, \sigma_g^2 \cdot \mathbf{K}) \qquad \epsilon \sim N(0, \sigma_e^2 \cdot \mathbf{I}_{n \times n})\]</span></p>
<div class="fragment">
<div class="r-stack">
<div class="fragment" style="background: #eaf4fb; border: 2px solid #2980b9; border-radius: 8px; padding: 0.4em 1.5em; text-align: center;">
<p><span class="math display">\[Y \sim N(\,\cdot\,,\; \cdot\,)\]</span></p>
</div>
<div class="fragment" style="background: #eaf4fb; border: 2px solid #2980b9; border-radius: 8px; padding: 0.4em 1.5em; text-align: center;">
<p><span class="math display">\[Y \sim N(X\beta,\; \sigma_g^2 \cdot \mathbf{K} + \sigma_e^2 \cdot \mathbf{I})\]</span></p>
</div>
</div>
<aside class="notes">
<p>Before we move on, let’s check understanding. If u is normal and ε is normal, what is Y = Xβ + u + ε?</p>
<p>The answer is also normal. The mean is Xβ — the fixed, deterministic part. The variance is the sum of the two random parts: σ²g · K from the genetic structure, plus σ²e · I from the independent residuals.</p>
<p>This is the core equation of the mixed effects model. Everything else — estimation, testing, software — is built on top of this distribution.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="setup-k-for-4-individuals-2-populations" class="slide level2">
<h2>Setup: K for 4 Individuals, 2 Populations</h2>

<img data-src="images/_page_17_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>Now let’s build intuition for what K actually looks like in a specific example. We have 4 individuals: individuals 1 and 2 are from AFR ancestry, individuals 3 and 4 from EUR ancestry.</p>
<p>The setup assigns one random effect value per population: u_AFR for both AFR individuals, u_EUR for both EUR individuals. We also assume the two population random effects are independent — AFR and EUR populations have separate genetic backgrounds.</p>
<p>From these simple assumptions, we can figure out what K must look like.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deriving-k-setting-up-the-variance" class="slide level2">
<h2>Deriving K — Setting Up the Variance</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot K = \text{Var}(u) \qquad \small\text{recall: } \text{Var}(u) = E(u - Eu)(u-Eu)' = Euu',\; E(u) = 0\]</span></p>
<p><span class="math display">\[\text{Var}\begin{bmatrix}u_1\\u_2\\u_3\\u_4\end{bmatrix} = Euu' = E\!\left(\begin{array}{ll}\begin{bmatrix}u_1\\u_2\\u_3\\u_4\end{bmatrix} &amp; \begin{array}{l}[u_1\;u_2\;u_3\;u_4]\\\phantom{u}\\\phantom{u}\\\phantom{u}\\\phantom{u}\end{array}\end{array}\right)\]</span></p>
<blockquote>
<p><span class="math inline">\(Eu_{\mathrm{AFR}} = Eu_{\mathrm{EUR}} = 0 \qquad Eu_{\mathrm{AFR}}^2 = Eu_{\mathrm{EUR}}^2 = \sigma_g^2 \qquad Eu_{\mathrm{AFR}} \cdot u_{\mathrm{EUR}} = 0\)</span></p>
</blockquote>
<aside class="notes">
<p>To find K, we need to compute the variance of the u vector. Variance of a vector is defined as E[uu’], where the prime means transpose.</p>
<p>Don’t worry too much about the matrix algebra here. The key insight is: Var(u) = E[uu’] is a 4×4 matrix where entry (i,j) is the expected product of u_i and u_j. That’s just a covariance — how much do individual i’s and individual j’s random effects move together?</p>
<p>The assumptions stated at the bottom do all the work: each u has variance σ²g, and u_AFR and u_EUR are independent (zero covariance).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deriving-k-expanding-the-outer-product" class="slide level2">
<h2>Deriving K — Expanding the Outer Product</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot K = \text{Var}(u) \qquad \small\text{recall: } \text{Var}(u) = E(u - Eu)(u-Eu)' = Euu',\; E(u) = 0\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot \mathbf{K} = E\begin{bmatrix} u_1 u_1 &amp; u_1 u_2 &amp; u_1 u_3 &amp; u_1 u_4 \\ u_2 u_1 &amp; u_2 u_2 &amp; u_2 u_3 &amp; u_2 u_4 \\ u_3 u_1 &amp; u_3 u_2 &amp; u_3 u_3 &amp; u_3 u_4 \\ u_4 u_1 &amp; u_4 u_2 &amp; u_4 u_3 &amp; u_4 u_4 \end{bmatrix}\]</span></p>
<p><em>expected value (<span class="math inline">\(E\)</span>) of a matrix is the <span class="math inline">\(E\)</span> of each element of the matrix</em></p>
<aside class="notes">
<p>When we multiply the column vector u by the row vector u’, we get a 4×4 matrix of products u_i · u_j. This is the outer product.</p>
<p>Taking the expectation of this matrix means taking the expectation of each entry separately. Entry (1,2) is E[u₁u₂], entry (1,3) is E[u₁u₃], and so on. Now we just need to fill in what each of those expectations equals given our assumptions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deriving-k-taking-expectations" class="slide level2">
<h2>Deriving K — Taking Expectations</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot K = \text{Var}(u) \qquad \small\text{recall: } \text{Var}(u) = E(u - Eu)(u-Eu)' = Euu',\; E(u) = 0\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot \mathbf{K} = \begin{bmatrix} Eu_1 u_1 &amp; Eu_1 u_2 &amp; Eu_1 u_3 &amp; Eu_1 u_4 \\ Eu_2 u_1 &amp; Eu_2 u_2 &amp; Eu_2 u_3 &amp; Eu_2 u_4 \\ Eu_3 u_1 &amp; Eu_3 u_2 &amp; Eu_3 u_3 &amp; Eu_3 u_4 \\ Eu_4 u_1 &amp; Eu_4 u_2 &amp; Eu_4 u_3 &amp; Eu_4 u_4 \end{bmatrix}\]</span></p>
<blockquote>
<p><span class="math inline">\(Eu_{\mathrm{AFR}} = Eu_{\mathrm{EUR}} = 0 \qquad Eu_{\mathrm{AFR}}^2 = Eu_{\mathrm{EUR}}^2 = \sigma_g^2 \qquad Eu_{\mathrm{AFR}} \cdot u_{\mathrm{EUR}} = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(u_1 = u_2 = u_{\mathrm{AFR}}~~~\)</span> and <span class="math inline">\(~~~u_3 = u_4 = u_{\mathrm{EUR}}\)</span></p>
</blockquote>
<aside class="notes">
<p>Now we apply the assumptions. Individuals 1 and 2 are both AFR, so u₁ = u₂ = u_AFR. Their product u₁u₂ = u²_AFR, and E[u²_AFR] = σ²g.</p>
<p>Individual 1 is AFR, individual 3 is EUR. Those are from different populations, so u₁ and u₃ are independent — E[u₁u₃] = E[u_AFR] · E[u_EUR] = 0 · 0 = 0.</p>
<p>So the off-diagonal blocks between AFR and EUR are all zeros; the diagonal blocks within each population are all σ²g.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deriving-k-final-result" class="slide level2">
<h2>Deriving K — Final Result</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot K = \text{Var}(u) \qquad \small\text{recall: } \text{Var}(u) = E(u - Eu)(u-Eu)' = Euu',\; E(u) = 0\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot \mathbf{K} = \sigma_g^2 \cdot \begin{bmatrix} 1 &amp; 1 &amp; 0 &amp; 0 \\ 1 &amp; 1 &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; 1 &amp; 1 \\ 0 &amp; 0 &amp; 1 &amp; 1 \end{bmatrix}\]</span></p>
<blockquote>
<p><span class="math inline">\(Eu_{\mathrm{AFR}} = Eu_{\mathrm{EUR}} = 0 \qquad Eu_{\mathrm{AFR}}^2 = Eu_{\mathrm{EUR}}^2 = \sigma_g^2 \qquad Eu_{\mathrm{AFR}} \cdot u_{\mathrm{EUR}} = 0\)</span></p>
</blockquote>
<blockquote>
<p><span class="math inline">\(u_1 = u_2 = u_{\mathrm{AFR}}~~~\)</span> and <span class="math inline">\(~~~u_3 = u_4 = u_{\mathrm{EUR}}\)</span></p>
</blockquote>
<aside class="notes">
<p>After all the expectations, we get K as a block matrix: 1s within the same population, 0s between populations. The σ²g cancels out from both sides.</p>
<p>This makes intuitive sense: individuals from the same population have K=1 (fully correlated background), individuals from different populations have K=0 (independent backgrounds). The model treats all AFR individuals as equally related to each other, and similarly for EUR.</p>
<p>In real data, of course, K isn’t a perfect block matrix — individuals within a population vary in how related they are, and that’s what the genomic relationship matrix captures.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-relatedness-matrix-grm-hapmap-trio-example" class="slide level2">
<h2>Genetic Relatedness Matrix (GRM) — HapMap Trio Example</h2>

<img data-src="images/_page_22_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p><a href="https://bios25328.hakyimlab.org/post/2021/02/18/l8-grm/">bios25328.hakyimlab.org/post/2021/02/18/l8-grm/</a></p>
</div>
<aside class="notes">
<p>Here’s what K looks like for a real dataset. This is the GRM computed from HapMap data for 6 individuals: 2 EUR trios and 2 AFR trios (a mother, father, and child from each population).</p>
<p>You can clearly see the block structure: within-population pairs (the large 6×6 blocks) have higher values than between-population pairs. Within each trio (the 3×3 blocks), relatedness is even higher — parents and children share ~50% of their genome.</p>
<p>A fun question: can you tell which individual in each trio is the child? The child shares ~50% of their genome with each parent, so they have higher GRM values with both parents than the parents have with each other. Look for the individual with the two highest off-diagonal values within a trio.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mixed-effects-correction-vs.-pc-vs.-genomic-control" class="slide level2">
<h2>Mixed Effects Correction vs.&nbsp;PC vs.&nbsp;Genomic Control</h2>

<img data-src="images/_page_23_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>Kang et al.&nbsp;<em>Variance component model to account for sample structure in genome-wide association studies.</em> Nature Genetics, 2010.</p>
</div>
<aside class="notes">
<p>This figure from Kang et al.&nbsp;2010 is the key validation of EMMAX (the mixed effects model software). Panel a compares uncorrected p-values (badly inflated) against 100-PC-corrected p-values and EMMAX-corrected p-values.</p>
<p>The striking result: EMMAX correction is very similar to genomic control in this dataset. Panel b shows the comparison directly. This tells us the mixed effects model is doing the job expected of genomic control — but it’s doing it in a principled, model-based way rather than a uniform scaling hack.</p>
<p>Notice the authors use λ itself as a goodness-of-fit measure to compare methods.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="combination-strategy-vs.-pure-mixed-effects" class="slide level2">
<h2>Combination Strategy vs.&nbsp;Pure Mixed Effects</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Combination strategy (common practice)</strong></p>
<ul>
<li>Remove close relatives</li>
<li>Correct broad sample structure with PCs</li>
<li>Correct residual inflation with genomic control (divide χ² by λ)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Mixed effects model</strong></p>
<ul>
<li>Use genetic relatedness matrix to account for all sample structure</li>
<li>PCs are eigenvectors of the GRM</li>
</ul>
<p><img data-src="images/_page_24_Figure_7.jpeg"></p>
</div></div>
<div class="fragment">
<div class="takehome">
<p>Mixed effects models are computationally expensive</p>
</div>
<aside class="notes">
<p>In practice today, most large GWAS don’t use pure mixed effects models. They use a combination: remove close relatives (to keep computational burden down), correct for broad ancestry structure with PCs, and apply genomic control as a final cleanup.</p>
<p>Why not always use the mixed effects model? Two reasons: (1) it’s computationally expensive — fitting a full GRM for 500K individuals requires solving large matrix equations; (2) it can sometimes over-correct, deflating true signals. (There are methods that address this deflation.)</p>
<p>The UK Biobank approach, for example, excluded over 100K individuals to remove close relatives before analysis. That’s a significant cost in sample size, but it keeps the analysis tractable.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="where-we-are" class="slide level2">
<h2>Where We Are</h2>
<p><strong>So far:</strong> Mixed effects models handle cryptic relatedness and family structure — answering open question 1</p>
<ul>
<li>Model: <span class="math inline">\(Y = X\beta + u + \epsilon\)</span>, where <span class="math inline">\(u \sim N(0, \sigma_g^2 \cdot K)\)</span></li>
<li>K encodes genetic similarity; correlated individuals share correlated background effects</li>
<li>In practice: remove close relatives + use PCs + genomic control as cleanup</li>
</ul>
<div class="fragment">
<p><strong>Open question 2 remains:</strong> When we see <span class="math inline">\(\lambda &gt; 1\)</span>, is it confounding — or real polygenicity?</p>
<ul>
<li>Genomic control can’t tell the difference</li>
<li>Dividing by <span class="math inline">\(\lambda\)</span> when the inflation is real signal throws away biology</li>
</ul>
</div>
<div class="fragment">
<p><strong>Next:</strong> LD score regression — a method that separates these two causes</p>
<aside class="notes">
<p>This is a good moment to pause and take stock. We’ve covered the mixed effects model — the principled answer to cryptic relatedness and family structure. In practice, most studies use a simpler combination strategy, but knowing the mixed effects model gives you the conceptual foundation.</p>
<p>Now we turn to the second open question: what does λ &gt; 1 actually mean in large studies? We’ll see that genomic control is dangerous when the trait is highly polygenic, and that LD score regression gives us a smarter way to distinguish real signal from confounding.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="ld-score-regression" class="title-slide slide level1 center">
<h1>LD Score Regression</h1>

</section>
<section id="what-is-a-statistic" class="slide level2">
<h2>What is a Statistic?</h2>
<p>To understand genomic control, we need to know what is a statistic.</p>
<p>In statistics terminology, a statistic is a function of the data</p>
<aside class="notes">
<p>Before diving into LD score regression, a quick conceptual anchor. In statistics, a “statistic” is simply any function computed from the data. The test statistic from a GWAS — whether it’s a Z-score, p-value, chi-squared, or beta — is just a different way of summarizing the same underlying association signal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="examples-of-statistics" class="slide level2">
<h2>Examples of Statistics</h2>

<img data-src="images/convert-between-statistics.png" class="r-stretch"><div class="source-credit">
<p><a href="https://bios25328.hakyimlab.org/post/2022/04/13/calculate-z-score-p-value-chi2-stat-from-gwas/">bios25328.hakyimlab.org/post/2022/04/13/calculate-z-score-p-value-chi2-stat-from-gwas/</a></p>
</div>
<aside class="notes">
<p>Z-scores, p-values, chi-squared statistics, and regression betas are all mathematically related — you can convert between them if you know the sample size. This figure shows those conversions.</p>
<p>This matters because GWAS summary statistics are shared publicly in many different formats. Knowing how to convert between them is a practical skill.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="inflation-of-test-statistics-two-causes" class="slide level2">
<h2>Inflation of Test Statistics: Two Causes</h2>

<img data-src="images/_page_26_Figure_0.jpeg" class="r-stretch"><p>Inflation of summary statistics can be due to:</p>
<ol type="1">
<li><strong>Confounders</strong> — population structure, cryptic relatedness</li>
<li><strong>True polygenicity</strong> — most variants have a causal effect or are in LD with causal variants</li>
</ol>
<p><strong>Genomic control cannot distinguish between these two.</strong> Dividing by λ punishes real signal.</p>
<aside class="notes">
<p>This is the conceptual heart of LD score regression. When we see λ &gt; 1 — more inflation than expected — there are two completely different explanations:</p>
<ol type="1">
<li><strong>Confounding</strong>: population structure or cryptic relatedness artificially inflates statistics. This is a bias we want to remove.</li>
<li><strong>True polygenicity</strong>: for a highly polygenic trait like height or schizophrenia, almost every common variant has a tiny causal effect. That’s real signal, not a bias.</li>
</ol>
<p>Genomic control can’t tell these apart — it just divides everything by λ. If the inflation is mostly polygenicity, genomic control throws away real signal. LD score regression was invented to solve this problem.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-and-chi²-statistics" class="slide level2">
<h2>LD and Chi² Statistics</h2>

<img data-src="images/_page_27_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>This plot shows chi-squared association statistics across a genomic region. Notice that high chi-squared statistics cluster in high-LD regions — SNPs that have many “LD friends.”</p>
<p>The intuition: if there’s a causal variant in a region, every SNP in LD with it will show some association — it’s tagging the causal variant. SNPs with more LD friends are more likely to be tagging a causal variant somewhere nearby, so they tend to have higher statistics on average.</p>
<p>This LD-dependence of test statistics is the signal that LD score regression exploits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-measure-of-ld-with-neighboring-variants" class="slide level2">
<h2>LD Score: Measure of LD with Neighboring Variants</h2>
<p><span class="math display">\[l_j = \sum_k r_{j,k}^2\]</span></p>
<ul>
<li><span class="math inline">\(l_j\)</span> = LD score of variant <span class="math inline">\(j\)</span></li>
<li>Measures amount of genetic variation <strong>tagged</strong> by variant <span class="math inline">\(j\)</span></li>
<li>SNPs in high-LD regions have high LD scores</li>
</ul>
<aside class="notes">
<p>The LD score for a SNP is simply the sum of its r² values with all nearby SNPs. It measures how many genetic variants a given SNP is tagging — how many “LD friends” it has.</p>
<p>SNPs in gene-dense, high-LD regions (like the MHC) have very high LD scores. SNPs in sparse, low-LD regions have low LD scores. This varies a lot across the genome.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polygenic-additive-model" class="slide level2">
<h2>Polygenic Additive Model</h2>
<p><span class="math display">\[Y = \sum_{k}^{M} X_k \cdot \beta_k + \epsilon \qquad \beta \sim N(0, \sigma_{\beta}^2)\]</span></p>
<ul>
<li>All <span class="math inline">\(M\)</span> common SNPs contribute to the phenotype</li>
<li>Effect sizes are drawn independently from a normal distribution</li>
<li>This is the main model for common disease genetics</li>
</ul>
<aside class="notes">
<p>The polygenic model assumes that all common SNPs contribute to phenotype, each with a tiny effect drawn from a normal distribution. This is the standard model for complex trait genetics.</p>
<p>Under this model, a SNP with a high LD score is expected to have a higher chi-squared statistic on average — not because it’s special itself, but because it’s tagging more causal variants scattered around it.</p>
<p>Importantly, confounding from population stratification does NOT have this property. Stratification affects all SNPs equally regardless of their LD structure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-distinguishes-confounding-from-polygenicity" class="slide level2">
<h2>LD Score Regression Distinguishes Confounding from Polygenicity</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1\]</span></p>
<ul>
<li><strong>Slope</strong> (<span class="math inline">\(Nh^2/M\)</span>): driven by true polygenicity → estimates <strong>heritability</strong></li>
<li><strong>Intercept</strong> (<span class="math inline">\(Na + 1\)</span>): driven by confounding → estimates <strong>population stratification / relatedness bias</strong></li>
</ul>

<img data-src="images/_page_30_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>This equation is the key result of Bulik-Sullivan et al.&nbsp;2015. On the left: the expected chi-squared statistic for SNP j. On the right: a linear function of the LD score l_j.</p>
<p>The slope (Nh²/M) tells us about true polygenicity and heritability. If there’s more real signal (higher h²), high-LD-score SNPs will have systematically higher statistics.</p>
<p>The intercept (Na + 1) tells us about confounding. Confounding inflates all statistics equally regardless of LD score — so it shows up as an elevated intercept, not a steeper slope.</p>
<p>By fitting this regression, we can quantify how much inflation is confounding and how much is real biology.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-parameters" class="slide level2">
<h2>LD Score Regression — Parameters</h2>

<img data-src="images/_page_32_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>A summary of what each parameter in the LDSC equation means. The key ones to internalize:</p>
<ul>
<li>N is sample size — bigger studies have larger slopes</li>
<li>h² is heritability — more heritable traits have steeper slopes</li>
<li>a is confounding — if a &gt; 0, there’s population stratification or cryptic relatedness bias</li>
<li>l_j is the LD score — the independent variable in the regression</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<table class="caption-top">
<colgroup>
<col style="width: 55%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(N\)</span></td>
<td>sample size</td>
</tr>
<tr class="even">
<td><span class="math inline">\(M\)</span></td>
<td>number of SNPs</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(h^2/M\)</span></td>
<td>variance explained per SNP</td>
</tr>
<tr class="even">
<td><span class="math inline">\(a\)</span></td>
<td>confounding: cryptic relatedness + population stratification</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(l_j = \sum_k r^2_{jk}\)</span></td>
<td>amount of genetic variation tagged by SNP <span class="math inline">\(j\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="ld-score-regression-schizophrenia" class="slide level2">
<h2>LD Score Regression — Schizophrenia</h2>

<img data-src="images/_page_33_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>Schizophrenia is one of the landmark applications of LDSC. The plot shows chi-squared statistics for schizophrenia GWAS SNPs plotted against their LD scores. The positive slope is clear — high-LD-score SNPs have higher statistics on average.</p>
<p>This is the signature of true polygenicity: the inflation is not random, it correlates with LD score. That’s what separates it from stratification.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genomic-control-vs.-ld-score-regression" class="slide level2">
<h2>Genomic Control vs.&nbsp;LD Score Regression</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 32%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (raw)</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (corrected)</th>
<th>LDSC intercept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ulcerative colitis</td>
<td>1.174</td>
<td>1.128</td>
<td>1.079 (0.010)</td>
</tr>
<tr class="even">
<td>Crohn’s disease</td>
<td>1.185</td>
<td>1.122</td>
<td>1.059 (0.008)</td>
</tr>
<tr class="odd">
<td>Schizophrenia</td>
<td>1.613</td>
<td>1.484</td>
<td>1.070 (0.010)</td>
</tr>
<tr class="even">
<td>ADHD</td>
<td>1.033</td>
<td>1.033</td>
<td>1.008 (0.006)</td>
</tr>
<tr class="odd">
<td>Bipolar disorder</td>
<td>1.154</td>
<td>1.135</td>
<td>1.030 (0.008)</td>
</tr>
<tr class="even">
<td>PGC cross-disorder</td>
<td>1.205</td>
<td>1.187</td>
<td>1.018 (0.008)</td>
</tr>
<tr class="odd">
<td>Major depression</td>
<td>1.063</td>
<td>1.063</td>
<td>1.009 (0.006)</td>
</tr>
<tr class="even">
<td>Rheumatoid arthritis</td>
<td>1.063</td>
<td>1.033</td>
<td>0.980 (0.007)</td>
</tr>
<tr class="odd">
<td>Coronary artery disease</td>
<td>1.125</td>
<td>1.096</td>
<td>1.033 (0.008)</td>
</tr>
<tr class="even">
<td>Type 2 diabetes</td>
<td>1.116</td>
<td>1.097</td>
<td>1.025 (0.008)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>This table is the key payoff. Look at schizophrenia: λ_GC = 1.613, which looks alarming. A naive analyst might conclude this GWAS is badly confounded. But the LDSC intercept is only 1.070 — almost all of the inflation is true polygenicity, not confounding.</p>
<p>If genomic control had been applied to correct for λ = 1.613, it would have discarded most of the real signal in the data. LDSC tells us: don’t correct this, it’s biology.</p>
<p>Contrast with ADHD, where λ ≈ 1.033 and the LDSC intercept ≈ 1.008. That’s a clean study with minimal confounding and (at the time) modest polygenicity signal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-values-on-chromosome-22" class="slide level2">
<h2>LD Score Values on Chromosome 22</h2>

<img data-src="images/_page_35_Figure_1.jpeg" class="r-stretch"><p>Calculated by Yanyu Liang using GTEx V8 reference variant set</p>
<aside class="notes">
<p>This plot shows how LD scores vary across chromosome 22. They’re not uniform — regions with more SNPs in LD with each other have higher scores. This spatial variation is what makes the LDSC regression work: we can regress against a variable (LD score) that differs systematically across the genome.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-between-traits" class="slide level2">
<h2>Genetic Correlation Between Traits</h2>

<img data-src="images/_page_36_Figure_0.jpeg" class="r-stretch"><p>With the same assumptions, LD score regression can estimate <strong>genetic correlation</strong> between traits:</p>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}}\]</span></p>
<aside class="notes">
<p>One of the most powerful extensions of LD score regression: estimating genetic correlation between two traits from their summary statistics alone.</p>
<p>The intuition is the same: if two traits share genetic architecture, then SNPs with high LD scores should have correlated Z-scores across both GWAS. By regressing the product of Z-scores on LD scores, we estimate how much of the genetic signal is shared.</p>
<p>This is a huge deal because it gives us genetic correlations without needing the raw data — just the public summary statistics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-estimates-h²-and-genetic-correlation" class="slide level2">
<h2>LD Score Regression Estimates h² and Genetic Correlation</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1 \quad \leftarrow \text{ heritability + confounders}\]</span></p>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}} \quad \leftarrow \text{ genetic correlation}\]</span></p>
<p>By partitioning LD scores into functional categories, we can also <strong>partition heritability by functional annotation</strong>.</p>
<aside class="notes">
<p>The same LDSC framework gives us three things from GWAS summary statistics: 1. Heritability (from the slope of the chi-squared vs.&nbsp;LD score regression) 2. Confounding bias (from the intercept) 3. Genetic correlation between traits (from the cross-trait Z-score product regression)</p>
<p>And as an extension: partitioned heritability by functional annotation — which parts of the genome (coding regions, enhancers, etc.) contribute most to heritability.</p>
<p>All of this from a simple regression of summary statistics against LD scores.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-cancers" class="slide level2">
<h2>Genetic Correlation Among Cancers</h2>
<aside class="notes">
<p>This table shows pairwise genetic correlations among six cancers estimated by LDSC. Most correlations are modest, but some are notable: colorectal and pancreatic cancer have a genetic correlation of 0.55, suggesting shared biology.</p>
<p>Breast and lung cancer show a genetic correlation of 0.27, which is interesting given how different these cancers are biologically. This raises hypotheses about shared risk factors or pathways.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Breast</th>
<th>Colorectal</th>
<th>Lung</th>
<th>Ovarian</th>
<th>Pancreatic</th>
<th>Prostate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Breast</td>
<td>1</td>
<td>0.22 (0.09)</td>
<td>0.27 (0.11)</td>
<td>0.26 (0.20)</td>
<td>0.17 (0.19)</td>
<td>0.06 (0.09)</td>
</tr>
<tr class="even">
<td>Colorectal</td>
<td>—</td>
<td>1</td>
<td>0.31 (0.10)</td>
<td>-0.08 (0.13)</td>
<td>0.55 (0.19)</td>
<td>0.09 (0.07)</td>
</tr>
<tr class="odd">
<td>Lung</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.17 (0.17)</td>
<td>0.32 (0.19)</td>
<td>0.095 (0.08)</td>
</tr>
<tr class="even">
<td>Ovarian</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.40 (0.29)</td>
<td>0.02 (0.14)</td>
</tr>
<tr class="odd">
<td>Pancreatic</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.06 (0.14)</td>
</tr>
<tr class="even">
<td>Prostate</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="source-credit">
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5582139/">ncbi.nlm.nih.gov/pmc/articles/PMC5582139/</a></p>
</div>
</section>
<section id="genetic-correlation-cancer-and-other-diseases" class="slide level2">
<h2>Genetic Correlation: Cancer and Other Diseases</h2>

<img data-src="images/_page_39_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>Describe the key patterns visible in the figure when presenting — which cancers show notable genetic correlations with non-cancer diseases, and what biological hypotheses that raises.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="caveat-assortative-mating-confounds-genetic-correlation" class="slide level2">
<h2>Caveat: Assortative Mating Confounds Genetic Correlation</h2>
<p><strong>Cross-trait assortative mating</strong> inflates genetic correlation estimates</p>
<div class="source-credit">
<p>Border et al.&nbsp;<em>Cross-trait assortative mating is widespread and inflates genetic correlation estimates.</em> Science, 2022.</p>
</div>
<aside class="notes">
<p>Genetic correlation estimates from LDSC can be inflated by a subtle confound: assortative mating. If people tend to partner with others who share similar traits — and those traits are genetically correlated — then the genomes of people in a population will have non-random correlations that mimic genetic correlation.</p>
<p>Border et al.&nbsp;2022 showed this is a real problem, especially for psychiatric traits. So genetic correlations from LDSC should be interpreted as estimates that may be upwardly biased for traits where assortative mating is common.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-psychiatric-diseases" class="slide level2">
<h2>Genetic Correlation Among Psychiatric Diseases</h2>

<img data-src="images/_page_41_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Brainstorm Consortium. <em>Analysis of shared heritability in common disorders of the brain.</em> Science, 2018.</p>
</div>
<aside class="notes">
<p>The Brainstorm Consortium estimated genetic correlations among 25 brain disorders using LDSC. The key finding: many psychiatric disorders are strongly genetically correlated with each other. ADHD, major depression, and bipolar disorder, for example, share substantial genetic architecture.</p>
<p>This suggests that the sharp diagnostic boundaries in psychiatry (DSM categories) don’t fully reflect the underlying biology. The genetics sees a more continuous landscape of shared risk.</p>
<p>Keep in mind the assortative mating caveat — psychiatric traits are exactly the ones most likely to be affected by cross-trait assortative mating.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="L6-beyond-pcs_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="L6-beyond-pcs_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>