<!DOCTYPE html>
<html lang="en"><head>
<script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/clipboard/clipboard.min.js"></script>
<script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/tabby.min.js"></script>
<script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/popper.min.js"></script>
<script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Hae Kyung Im, PhD">
  <meta name="dcterms.date" content="2025-04-14">
  <title>Mixed Effects Models &amp; LD Score Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="../custom.css">
  <link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Mixed Effects Models &amp; LD Score Regression</h1>
  <p class="subtitle">BIOS 25328 · Lecture 6</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Hae Kyung Im, PhD 
</div>
</div>
</div>

  <p class="date">2025-04-14</p>
</section>
<section id="last-weeks-recap" class="slide level2">
<h2>Last week’s recap</h2>
<p>We covered how population structure can bias GWAS results and how to correct for it</p>
<ul>
<li>Genetic <strong>principal components</strong> capture ancestry from the genotype matrix</li>
<li>Top PCs added as covariates correct for population stratification</li>
<li>Four methods: genomic control, latent subpopulations, PCs, mixed effects models</li>
</ul>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<ol type="1">
<li>Understand <strong>genomic control</strong> (λ inflation factor) and its limitations</li>
<li>Derive the <strong>mixed effects model</strong> for population structure correction</li>
<li>Understand the <strong>kinship/GRM</strong> as a random effect covariance structure</li>
<li>Learn how <strong>LD score regression</strong> separates true polygenicity from confounding</li>
<li>Interpret <strong>genetic correlation</strong> estimates from LD score regression</li>
</ol>
</section>
<section>
<section id="how-to-correct-for-population-structure" class="title-slide slide level1 center">
<h1>How to Correct for Population Structure</h1>

</section>
<section id="approaches-to-correct-for-population-structure" class="slide level2">
<h2>Approaches to Correct for Population Structure</h2>
<ol type="1">
<li><strong>Genomic control</strong> (Devlin &amp; Roeder 1999) — now superseded by LD score regression</li>
<li><strong>Infer latent sub-populations</strong> (Pritchard et al.&nbsp;2000) — fit association in each population separately and combine</li>
<li><strong>Adjust for principal components</strong> (Patterson 2006; Price et al.&nbsp;2010) ← <em>most common today</em></li>
<li><strong>Mixed effects modeling</strong> (EMMAX, Kang et al.&nbsp;2010)</li>
</ol>
<aside class="notes">
<p>Genomic control is a simple approach broadly used. As sample sizes increase, we need to revisit this approach. If we know the subpopulations, we can run the GWAS within each and meta-analyze. PCA covariates are the most common approach today. Mixed effects modeling is the focus of this lecture.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genomic-control-devlin-roeder-1999" class="slide level2">
<h2>1. Genomic Control (Devlin &amp; Roeder, 1999)</h2>
<ul>
<li><strong>Assumption</strong>: effects of population stratification and cryptic relatedness are <strong>constant across the genome</strong></li>
<li>Test statistics are distributed <span class="math inline">\(\lambda \times \chi^2\)</span></li>
<li>Estimate <span class="math inline">\(\lambda\)</span> using:
<ul>
<li>Mean of test statistics, or</li>
<li>Median: <span class="math inline">\(\lambda = \text{median}(\chi^2) / 0.4549\)</span></li>
</ul></li>
<li><span class="math inline">\(\lambda &lt; 1.05\)</span> considered acceptable inflation</li>
</ul>
<aside class="notes">
<p>Population stratification leads to inflation of false positives — more small p-values than we would expect under a uniform distribution. The genomic control method corrects for this by dividing all chi-squared statistics by the inflation factor λ. Using the median is more robust to true signals with large chi-squared statistics that could skew the mean.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="gwas-summary-statistics-z-score" class="slide level2">
<h2>GWAS Summary Statistics → Z-score</h2>
<p><span class="math display">\[Y = \beta \cdot X + \epsilon\]</span></p>
<p>GWAS summary statistics report <span class="math inline">\(\hat{\beta}\)</span> (effect size) and <span class="math inline">\(\text{se}(\hat{\beta})\)</span> (standard error) for each SNP.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Z-score</strong> (standardized effect)</p>
<p><span class="math display">\[Z = \frac{\hat{\beta}}{\text{se}(\hat{\beta})}\]</span></p>
<p><span class="math display">\[Z \approx N(0,1) \quad \text{as } n \to \infty\]</span></p>
</div><div class="column" style="width:50%;">
<p><strong>Chi-squared</strong> (squared Z)</p>
<p><span class="math display">\[Z^2 \sim \chi^2_{df=1}\]</span></p>
<p>Under the null, the squared Z-score follows a χ² with 1 degree of freedom.</p>
</div></div>
<aside class="notes">
<p>We distinguish the true β from the estimated β-hat using a hat. The Z-score is the key statistic — it standardizes the effect size by its uncertainty.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="converting-between-test-statistics" class="slide level2">
<h2>Converting Between Test Statistics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Z → P-value</strong></p>
<p><span class="math display">\[P = \text{pnorm}(-|Z|) \times 2\]</span></p>
<p><strong>P → Z</strong> <em>(sign is lost)</em></p>
<p><span class="math display">\[|Z| = |\text{qnorm}(P/2)|\]</span></p>
<p>The Z-score carries more information than the p-value — the sign encodes direction of effect.</p>
</div><div class="column" style="width:50%;">
<p><strong>P → Chi²</strong></p>
<p><span class="math display">\[\chi^2 = \text{qnorm}(P/2)^2\]</span></p>
<p><strong>Summary</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Have</th>
<th>Get</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{\beta}\)</span>, <span class="math inline">\(\text{se}\)</span></td>
<td><span class="math inline">\(Z\)</span>, <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(P\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Z\)</span></td>
<td><span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(P\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P\)</span></td>
<td><span class="math inline">\(|Z|\)</span>, <span class="math inline">\(\chi^2\)</span></td>
</tr>
</tbody>
</table>
</div></div>
<div class="source-credit">
<p><a href="https://bios25328.hakyimlab.org/post/2022/04/13/calculate-z-score-p-value-chi2-stat-from-gwas/">bios25328.hakyimlab.org/post/2022/04/13/calculate-z-score-p-value-chi2-stat-from-gwas/</a></p>
</div>
</section>
<section id="chi²-inflation-from-population-stratification" class="slide level2">
<h2>Chi² Inflation from Population Stratification</h2>

<img data-src="images/_page_6_Figure_0.jpeg" class="r-stretch quarto-figure-center"><p class="caption">Simulated case-control study with cases from one population and controls from another. Uncorrected chi-squared statistics (black) vs.&nbsp;genomic-control-corrected (green)</p><aside class="notes">
<p>Here all SNPs that have different frequencies between populations will be significantly associated with case-control status. Green dots correspond to corrected chi² with genomic control (λ = mean(obs chi²) / mean(expected chi²)).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="q-q-plots-observed-vs.-expected-χ²" class="slide level2">
<h2>Q-Q Plots: Observed vs.&nbsp;Expected χ²</h2>

<img data-src="images/_page_6_Figure_1.jpeg" class="r-stretch"></section>
<section id="simulated-stratification-raw-chi²-statistics" class="slide level2">
<h2>Simulated Stratification — Raw Chi² Statistics</h2>

<img data-src="images/_page_7_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>A dumb case-control study with all cases from one population and all controls from another. Chi-squared of these associations before and after genomic control correction. One can also adjust with medians to keep it robust to outliers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="function-to-calculate-genomic-control" class="slide level2">
<h2>Function to Calculate Genomic Control</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="do">## Reads data</span></span>
<span id="cb1-2"><a href=""></a>S <span class="ot">&lt;-</span> <span class="fu">read.table</span>(input, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href=""></a><span class="cf">if</span> (stat_type <span class="sc">==</span> <span class="st">"Z"</span>)</span>
<span id="cb1-4"><a href=""></a>  z <span class="ot">=</span> S[, <span class="dv">1</span>]</span>
<span id="cb1-5"><a href=""></a><span class="cf">if</span> (stat_type <span class="sc">==</span> <span class="st">"CHISQ"</span>)</span>
<span id="cb1-6"><a href=""></a>  z <span class="ot">=</span> <span class="fu">sqrt</span>(S[, <span class="dv">1</span>])</span>
<span id="cb1-7"><a href=""></a><span class="cf">if</span> (stat_type <span class="sc">==</span> <span class="st">"PVAL"</span>)</span>
<span id="cb1-8"><a href=""></a>  z <span class="ot">=</span> <span class="fu">qnorm</span>(S[, <span class="dv">1</span>] <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb1-9"><a href=""></a></span>
<span id="cb1-10"><a href=""></a><span class="do">## calculates lambda</span></span>
<span id="cb1-11"><a href=""></a>lambda <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">median</span>(z<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fl">0.4549</span>, <span class="dv">3</span>)</span>
<span id="cb1-12"><a href=""></a>lambda</span>
<span id="cb1-13"><a href=""></a><span class="co"># Where 0.4549 is the median of a chi2 r.v. with 1 df</span></span>
<span id="cb1-14"><a href=""></a><span class="co"># qchisq(0.5, 1) = 0.4549364</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<aside class="notes">
<p>This function calculates the genomic control λ given Z-scores, Chi², or p-values in a data frame. The divisor 0.4549 is the median of a chi-squared distribution with 1 degree of freedom.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="infer-latent-population-structure" class="slide level2">
<h2>2. Infer Latent Population Structure</h2>
<ul>
<li>Infer latent population structure (e.g.&nbsp;STRUCTURE, Pritchard et al.)</li>
<li>Perform association in each sub-population and aggregate using meta-analysis</li>
</ul>

<img data-src="images/_page_9_Figure_4.jpeg" class="r-stretch"><aside class="notes">
<p>We can infer the latent subpopulations with methods such as STRUCTURE or others, perform association within each subpopulation, then meta-analyze to get the full population association statistics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="adjust-with-principal-components" class="slide level2">
<h2>3. Adjust with Principal Components</h2>
<p><em>Most common approach — covered last lecture</em></p>
<p><span class="math display">\[Y \sim X_k\beta^k + \text{PC}^1 + \cdots + \text{PC}^p + \epsilon\]</span></p>
<ul>
<li>Simple and effective for broad population stratification</li>
<li>Top PCs act as covariates capturing ancestry</li>
</ul>
</section></section>
<section>
<section id="mixed-effects-models" class="title-slide slide level1 center">
<h1>Mixed Effects Models</h1>

</section>
<section id="adjusting-for-population-structure-with-mixed-effects-models" class="slide level2">
<h2>Adjusting for Population Structure with Mixed Effects Models</h2>
<h4 id="kang-et-al.-variance-component-model-emmax">Kang et al.&nbsp;— Variance Component Model (EMMAX)</h4>
<p><span class="math display">\[Y = X\beta + u + \epsilon\]</span></p>
<p><span class="math display">\[u \sim N(0,\, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<ul>
<li><span class="math inline">\(\beta\)</span> = <strong>fixed</strong> effect (SNP effect of interest)</li>
<li><span class="math inline">\(u\)</span> = <strong>random</strong> effect (captures population/family structure)</li>
<li><span class="math inline">\(\mathbf{K}\)</span> = genetic relatedness matrix (GRM)</li>
</ul>
<p>Useful to adjust for confounding due to <strong>population structure</strong>, <strong>family structure</strong>, and <strong>cryptic relatedness</strong></p>
<div class="source-credit">
<p>Kang et al.&nbsp;<em>Variance component model to account for sample structure in genome-wide association studies.</em> Nature Genetics, 2010.</p>
</div>
<aside class="notes">
<p>Mixed effects models are regression models with both fixed and random effects. β is a fixed effect; u is a random effect specified by its distribution. When K is the genetic relatedness matrix, this model accounts for population structure, family structure, and cryptic relatedness.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-vectors" class="slide level2">
<h2>Example with 4 Individuals — Vectors</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vectors for 4 individuals:</p>
<p><span class="math display">\[\begin{bmatrix} y_1 \\ y_2 \\ y_3 \\ y_4 \end{bmatrix} = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{bmatrix} \cdot \beta + \begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \end{bmatrix} + \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \epsilon_3 \\ \epsilon_4 \end{bmatrix}\]</span></p>
<p><span class="math display">\[Y \sim N(X\beta,\; \sigma_g^2 \cdot \mathbf{K} + \sigma_e^2 \cdot \mathbf{I})\]</span></p>
<aside class="notes">
<p>A simple example with 4 individuals: two from EUR ancestry and two from AFR ancestry, no family structure or cryptic relatedness. Here u represents the effect of population membership on phenotype Y. K represents the population pattern; σ_g is the scale of that effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-random-effect-u" class="slide level2">
<h2>Example with 4 Individuals — Random Effect <em>u</em></h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vector <span class="math inline">\(u\)</span> and its variance matrix:</p>
<p><span class="math display">\[\begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \end{bmatrix} \sim N \left( \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix},\; \sigma_g^2 \cdot \begin{bmatrix} k_{11} &amp; k_{12} &amp; k_{13} &amp; k_{14} \\ k_{21} &amp; k_{22} &amp; k_{23} &amp; k_{24} \\ k_{31} &amp; k_{32} &amp; k_{33} &amp; k_{34} \\ k_{41} &amp; k_{42} &amp; k_{43} &amp; k_{44} \end{bmatrix} \right)\]</span></p>
<p><span class="math inline">\(u\)</span> is a multivariate normal random variable</p>
<aside class="notes">
<p>The random effect u is multivariate normal with mean 0 and variance σ²_g · K. The matrix K encodes the genetic similarity between individuals.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-with-4-individuals-residual-ε" class="slide level2">
<h2>Example with 4 Individuals — Residual <em>ε</em></h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p>Spell out the vector <span class="math inline">\(\epsilon\)</span> and its variance matrix:</p>
<p><span class="math display">\[\begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \epsilon_3 \\ \epsilon_4 \end{bmatrix} \sim N \left( \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix},\; \sigma_e^2 \cdot \begin{bmatrix} 1 &amp; 0 &amp; 0 &amp; 0 \\ 0 &amp; 1 &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; 1 &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; 1 \end{bmatrix} \right)\]</span></p>
<p><span class="math inline">\(\epsilon\)</span> is a multivariate normal random variable</p>
<aside class="notes">
<p>Epsilon is also multivariate normal with variance σ²_e · I. The identity matrix means residuals are independent across individuals — the random effect u captures the correlated structure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="checkpoint-what-is-the-distribution-of-y" class="slide level2">
<h2>Checkpoint: What is the Distribution of Y?</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon\]</span></p>
<p><span class="math display">\[u \sim N(0, \sigma_g^2 \cdot \mathbf{K}) \qquad \epsilon \sim N(0, \sigma_e^2 \cdot \mathbf{I}_{n \times n})\]</span></p>

<img data-src="images/_page_17_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>Since u and ε are both normal and independent, their sum is also normal. Y ~ N(Xβ, σ²_g · K + σ²_e · I).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="deriving-k-for-2-eur-2-afr-individuals" class="slide level2">
<h2>Deriving K for 2 EUR + 2 AFR Individuals</h2>
<p><span class="math display">\[Y = X\beta + u + \epsilon \qquad u \sim N(0, \sigma_g^2 \cdot \mathbf{K})\]</span></p>
<p><span class="math display">\[\sigma_g^2 \cdot K = \text{Var}(u) = E\,uu'\]</span></p>
<p>Assume individuals 1 &amp; 2 are AFR, individuals 3 &amp; 4 are EUR, populations are independent:</p>
<p><span class="math display">\[E\,u_{\rm AFR} = E\,u_{\rm EUR} = 0\]</span></p>
<p><span class="math display">\[E\,u_{\rm AFR}^2 = E\,u_{\rm EUR}^2 = \sigma_g^2 \qquad E\,u_{\rm AFR} \cdot u_{\rm EUR} = 0\]</span></p>
<p>Therefore:</p>
<p><span class="math display">\[\sigma_g^2 \cdot \mathbf{K} = \sigma_g^2 \cdot \begin{bmatrix} 1 &amp; 1 &amp; 0 &amp; 0 \\ 1 &amp; 1 &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; 1 &amp; 1 \\ 0 &amp; 0 &amp; 1 &amp; 1 \end{bmatrix}\]</span></p>
<aside class="notes">
<p>This is how the variance matrix of the random effect that captures population-level variation looks like. Within-population pairs share the same random effect; between-population pairs are independent.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-relatedness-matrix-grm-hapmap-example" class="slide level2">
<h2>Genetic Relatedness Matrix (GRM) — HapMap Example</h2>

<img data-src="images/_page_22_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p><a href="https://bios25328.hakyimlab.org/post/2021/02/18/l8-grm/">bios25328.hakyimlab.org/post/2021/02/18/l8-grm/</a></p>
</div>
<aside class="notes">
<p>GRM of 2 European and 2 African trios (mother, father, child) from HapMap (YRI, CEU) calculated using plink’s –make-grm-gz. The 6×6 population blocks are visible, and the 3×3 family blocks (trios) are nested within them. Random mating within populations is a reasonable assumption. Can you identify which individual is the child within each trio?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="emmax-correction-vs.-principal-components" class="slide level2">
<h2>EMMAX Correction vs.&nbsp;Principal Components</h2>

<img data-src="images/_page_23_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>Kang et al.&nbsp;compare uncorrected p-values (inflated), p-values corrected for 100 PCs (eigensoft), and EMMAX-corrected p-values. Panel b compares EMMAX to simple genomic control, showing similar correction. Notice that the authors use genomic control as a measure of goodness of fit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="combination-strategy-vs.-pure-mixed-effects" class="slide level2">
<h2>Combination Strategy vs.&nbsp;Pure Mixed Effects</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Combination strategy (common practice)</strong></p>
<ul>
<li>Remove close relatives</li>
<li>Correct broad sample structure with PCs</li>
<li>Correct residual inflation with genomic control (divide χ² by λ)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Mixed effects model</strong></p>
<ul>
<li>Use genetic relatedness matrix to account for all sample structure</li>
<li>PCs are eigenvectors of the GRM</li>
</ul>
<p><img data-src="images/_page_24_Figure_7.jpeg"></p>
</div></div>
<aside class="notes">
<p>Mixed effects models are powerful but computationally expensive and can sometimes over-correct (deflation). Still today, the simpler approach of removing close relatives is common — in UK Biobank studies, over 100K individuals have been excluded to avoid relatedness.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="ld-score-regression" class="title-slide slide level1 center">
<h1>LD Score Regression</h1>

</section>
<section id="inflation-of-test-statistics-two-causes" class="slide level2">
<h2>Inflation of Test Statistics: Two Causes</h2>

<img data-src="images/_page_26_Figure_0.jpeg" class="r-stretch"><p>Inflation of summary statistics can be due to:</p>
<ol type="1">
<li><strong>Confounders</strong> — population structure, relatedness, etc.</li>
<li><strong>True polygenicity</strong> — most variants have a causal effect or are in LD with causal variants</li>
</ol>
<p>Genomic control <strong>cannot distinguish</strong> between these two sources of inflation.</p>
<aside class="notes">
<p>Genomic control divides all statistics by λ, which over-corrects if the inflation is due to true polygenicity. LD score regression provides a way to separate these two contributions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-and-chi²-statistics" class="slide level2">
<h2>LD and Chi² Statistics</h2>

<img data-src="images/_page_27_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>A locus-zoom-like plot with chi-squared statistics instead of p-values. Variants in high-LD regions have higher association statistics — they tag more causal variants. Variants with many “LD friends” are lifted up because they are more likely to tag causal variants.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-measure-of-ld-with-neighboring-variants" class="slide level2">
<h2>LD Score: Measure of LD with Neighboring Variants</h2>
<p><span class="math display">\[l_j = \sum_k r_{j,k}^2\]</span></p>
<ul>
<li><span class="math inline">\(l_j\)</span> = LD score of variant <span class="math inline">\(j\)</span></li>
<li>Measures amount of genetic variation <strong>tagged</strong> by variant <span class="math inline">\(j\)</span></li>
<li>SNPs in high-LD regions have high LD scores</li>
</ul>
<aside class="notes">
<p>The LD score is the number of “LD friends” — calculated as the sum of r² with all neighboring variants. Each genetic variant has one LD score.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polygenic-additive-model" class="slide level2">
<h2>Polygenic Additive Model</h2>
<p><span class="math display">\[Y = \sum_{k}^{M} X_k \cdot \beta_k + \epsilon \qquad \beta \sim N(0, \sigma_{\beta}^2)\]</span></p>
<ul>
<li>All <span class="math inline">\(M\)</span> common SNPs contribute to the phenotype</li>
<li>Effect sizes are drawn independently from a normal distribution</li>
<li>This is the main model for common disease genetics</li>
</ul>
<aside class="notes">
<p>Under this polygenic model, variants in high-LD regions are more likely to tag causal variants, so they will have higher chi-squared statistics on average. This is the key insight underlying LD score regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-distinguishes-confounding-from-polygenicity" class="slide level2">
<h2>LD Score Regression Distinguishes Confounding from Polygenicity</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1\]</span></p>
<ul>
<li><strong>Slope</strong> (<span class="math inline">\(Nh^2/M\)</span>): driven by true polygenicity → estimates <strong>heritability</strong></li>
<li><strong>Intercept</strong> (<span class="math inline">\(Na + 1\)</span>): driven by confounding → estimates <strong>population stratification / relatedness bias</strong></li>
</ul>

<img data-src="images/_page_30_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>Bulik-Sullivan et al.&nbsp;show we can distinguish inflation due to confounding (flat line, intercept &gt; 1) from polygenicity (positive slope proportional to LD score). Variants in high-LD regions have higher chi-squared due to tagging more causal variants. Inflation from cryptic relatedness or population stratification from genetic drift does NOT correlate with LD score.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-parameters" class="slide level2">
<h2>LD Score Regression — Parameters</h2>

<img data-src="images/_page_32_Figure_1.jpeg" class="r-stretch"><table class="caption-top">
<colgroup>
<col style="width: 55%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(N\)</span></td>
<td>sample size</td>
</tr>
<tr class="even">
<td><span class="math inline">\(M\)</span></td>
<td>number of SNPs</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(h^2/M\)</span></td>
<td>variance explained per SNP</td>
</tr>
<tr class="even">
<td><span class="math inline">\(a\)</span></td>
<td>confounding: cryptic relatedness + population stratification</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(l_j = \sum_k r^2_{jk}\)</span></td>
<td>amount of genetic variation tagged by SNP <span class="math inline">\(j\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="ld-score-regression-schizophrenia" class="slide level2">
<h2>LD Score Regression — Schizophrenia</h2>

<img data-src="images/_page_33_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>Schizophrenia has a very high LD score regression intercept, indicating substantial true polygenicity in addition to any confounding. The positive slope shows that SNPs with more LD friends have systematically higher chi-squared statistics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genomic-control-vs.-ld-score-regression" class="slide level2">
<h2>Genomic Control vs.&nbsp;LD Score Regression</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 32%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (raw)</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (corrected)</th>
<th>LDSC intercept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ulcerative colitis</td>
<td>1.174</td>
<td>1.128</td>
<td>1.079 (0.010)</td>
</tr>
<tr class="even">
<td>Crohn’s disease</td>
<td>1.185</td>
<td>1.122</td>
<td>1.059 (0.008)</td>
</tr>
<tr class="odd">
<td>Schizophrenia</td>
<td>1.613</td>
<td>1.484</td>
<td>1.070 (0.010)</td>
</tr>
<tr class="even">
<td>ADHD</td>
<td>1.033</td>
<td>1.033</td>
<td>1.008 (0.006)</td>
</tr>
<tr class="odd">
<td>Bipolar disorder</td>
<td>1.154</td>
<td>1.135</td>
<td>1.030 (0.008)</td>
</tr>
<tr class="even">
<td>PGC cross-disorder</td>
<td>1.205</td>
<td>1.187</td>
<td>1.018 (0.008)</td>
</tr>
<tr class="odd">
<td>Major depression</td>
<td>1.063</td>
<td>1.063</td>
<td>1.009 (0.006)</td>
</tr>
<tr class="even">
<td>Rheumatoid arthritis</td>
<td>1.063</td>
<td>1.033</td>
<td>0.980 (0.007)</td>
</tr>
<tr class="odd">
<td>Coronary artery disease</td>
<td>1.125</td>
<td>1.096</td>
<td>1.033 (0.008)</td>
</tr>
<tr class="even">
<td>Type 2 diabetes</td>
<td>1.116</td>
<td>1.097</td>
<td>1.025 (0.008)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Notice that the LDSC intercept is systematically smaller than the genomic control λ. For schizophrenia, λ=1.613 looks alarming, but the LDSC intercept is only 1.070 — most of the inflation is true polygenicity, not confounding. Genomic control would have over-corrected.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-values-on-chromosome-22" class="slide level2">
<h2>LD Score Values on Chromosome 22</h2>

<img data-src="images/_page_35_Figure_1.jpeg" class="r-stretch"><p>Calculated by Yanyu Liang using GTEx V8 reference variant set</p>
<aside class="notes">
<p>LD scores vary considerably across the chromosome, reflecting the local LD structure. Regions with high LD have high LD scores; sparse regions have low LD scores.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-between-traits" class="slide level2">
<h2>Genetic Correlation Between Traits</h2>

<img data-src="images/_page_36_Figure_0.jpeg" class="r-stretch"><p>With the same assumptions, LD score regression can estimate <strong>genetic correlation</strong> between traits:</p>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}}\]</span></p>
<aside class="notes">
<p>By regressing the product of Z-scores of two traits against LD scores, we can estimate their genetic correlation. This avoids confounders in observational studies and provides orthogonal evidence for associations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-estimates-h²-and-genetic-correlation" class="slide level2">
<h2>LD Score Regression Estimates h² and Genetic Correlation</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1 \quad \leftarrow \text{ heritability + confounders}\]</span></p>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}} \quad \leftarrow \text{ genetic correlation}\]</span></p>
<p>By partitioning LD scores into functional categories, we can also <strong>partition heritability by functional annotation</strong>.</p>
<aside class="notes">
<p>The same LD score regression framework extends to estimate: heritability, confounding bias, genetic correlation between traits, and partitioned heritability by functional category. This is a very powerful unified framework from a single GWAS run.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-cancers" class="slide level2">
<h2>Genetic Correlation Among Cancers</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Breast</th>
<th>Colorectal</th>
<th>Lung</th>
<th>Ovarian</th>
<th>Pancreatic</th>
<th>Prostate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Breast</td>
<td>1</td>
<td>0.22 (0.09)</td>
<td>0.27 (0.11)</td>
<td>0.26 (0.20)</td>
<td>0.17 (0.19)</td>
<td>0.06 (0.09)</td>
</tr>
<tr class="even">
<td>Colorectal</td>
<td>—</td>
<td>1</td>
<td>0.31 (0.10)</td>
<td>-0.08 (0.13)</td>
<td>0.55 (0.19)</td>
<td>0.09 (0.07)</td>
</tr>
<tr class="odd">
<td>Lung</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.17 (0.17)</td>
<td>0.32 (0.19)</td>
<td>0.095 (0.08)</td>
</tr>
<tr class="even">
<td>Ovarian</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.40 (0.29)</td>
<td>0.02 (0.14)</td>
</tr>
<tr class="odd">
<td>Pancreatic</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.06 (0.14)</td>
</tr>
<tr class="even">
<td>Prostate</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="source-credit">
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5582139/">ncbi.nlm.nih.gov/pmc/articles/PMC5582139/</a></p>
</div>
</section>
<section id="genetic-correlation-cancer-and-other-diseases" class="slide level2">
<h2>Genetic Correlation: Cancer and Other Diseases</h2>

<img data-src="images/_page_39_Figure_1.jpeg" class="r-stretch"></section>
<section id="caveat-assortative-mating-confounds-genetic-correlation" class="slide level2">
<h2>Caveat: Assortative Mating Confounds Genetic Correlation</h2>
<p><strong>Cross-trait assortative mating</strong> inflates genetic correlation estimates</p>
<div class="source-credit">
<p>Border et al.&nbsp;<em>Cross-trait assortative mating is widespread and inflates genetic correlation estimates.</em> Science, 2022.</p>
</div>
<aside class="notes">
<p>If people mate non-randomly based on traits that are genetically correlated, this creates spurious genetic correlations. The Brainstorm Consortium and Border et al.&nbsp;show this is a real concern for psychiatric disorders.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-psychiatric-diseases" class="slide level2">
<h2>Genetic Correlation Among Psychiatric Diseases</h2>

<img data-src="images/_page_41_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Brainstorm Consortium. <em>Analysis of shared heritability in common disorders of the brain.</em> Science, 2018.</p>
</div>
<aside class="notes">
<p>The Brainstorm Consortium estimated genetic correlations among 25 brain disorders. Many psychiatric disorders show high genetic correlations with each other, suggesting shared biological mechanisms.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="L6-Mixed-Effects-Models-LDSC-2025_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>