<!DOCTYPE html>
<html lang="en"><head>
<script src="L8-eQTL-finemapping-enrichment_files/libs/clipboard/clipboard.min.js"></script>
<script src="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/tabby.min.js"></script>
<script src="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/popper.min.js"></script>
<script src="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="L8-eQTL-finemapping-enrichment_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Hae Kyung Im, PhD">
  <meta name="dcterms.date" content="2026-04-15">
  <title>eQTL Analysis, Fine-Mapping, and Heritability Enrichment</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="custom.css">
  <link href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">eQTL Analysis, Fine-Mapping, and Heritability Enrichment</h1>
  <p class="subtitle">BIOS 25328 · Lecture 8</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Hae Kyung Im, PhD 
</div>
</div>
</div>

  <p class="date">2026-04-15</p>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<p>In this lecture we first cover LD score regression (material from L6 that deserves more time), then quantify where heritability lives in the genome, and finally use eQTLs as functional annotations that help elucidate the mechanisms underlying GWAS loci.</p>
<ul>
<li>Explain how LD score regression distinguishes true polygenicity from confounding</li>
<li>Estimate heritability and genetic correlation from GWAS summary statistics using LDSC</li>
<li>Use stratified LD score regression to partition heritability by functional annotation</li>
<li>Define eQTLs and sQTLs and explain the GTEx study design</li>
<li>Use eQTLs as functional annotations to elucidate mechanisms underlying GWAS loci</li>
<li>Understand how fine-mapping narrows associations to likely causal variants</li>
</ul>
<aside class="notes">
<p>This lecture opens with LD score regression — material introduced in L6 but not covered in enough depth there. We then extend it to stratified LDSC, which quantifies how much heritability is enriched in functional genomic regions. The second half introduces eQTLs as functional annotations: variants that associate with gene expression levels, which helps explain how non-coding GWAS loci influence complex traits. The through-line: heritability is enriched in regulatory elements → eQTLs map genetic effects on gene regulation → they serve as functional evidence linking GWAS loci to mechanisms.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="ld-score-regression" class="title-slide slide level1 center">
<h1>LD Score Regression</h1>
<div class="callout callout-note no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>These slides were introduced in L6 (Mixed Effects Models) but were not covered in sufficient depth. We revisit them here before extending to stratified LDSC.</p>
</div>
</div>
</div>
</section>
<section id="inflation-of-test-statistics-two-causes" class="slide level2">
<h2>Inflation of Test Statistics: Two Causes</h2>
<div class="columns">
<div class="column" style="width:65%;">
<p><img data-src="images/_page_26_Figure_0.jpeg"></p>
</div><div class="column" style="font-size: 0.75em;">
<p>Inflation of summary statistics can be due to:</p>
<ol type="1">
<li><strong>Confounders</strong> — population structure, relatedness, etc.</li>
<li><strong>True polygenicity</strong> — most variants have a causal effect or are in LD with causal variants</li>
</ol>
<div class="source-credit">
<p>Bulik-Sullivan et al.&nbsp;Nature Genetics, 2015.</p>
</div>
</div></div>
<div class="takehome">
<p>Genomic control cannot distinguish between true polygenicity and confounding</p>
</div>
<aside class="notes">
<p>Genomic control divides all statistics by λ, which over-corrects if the inflation is due to true polygenicity. LD score regression provides a way to separate these two contributions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-and-chi²-statistics" class="slide level2">
<h2>LD and Chi² Statistics</h2>

<img data-src="images/_page_27_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>A locus-zoom-like plot with chi-squared statistics instead of p-values. Variants in high-LD regions have higher association statistics — they tag more causal variants. Variants with many “LD friends” are lifted up because they are more likely to tag causal variants.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-measure-of-ld-with-neighboring-variants" class="slide level2">
<h2>LD Score: Measure of LD with Neighboring Variants</h2>
<p><span class="math display">\[l_j = \sum_k r_{j,k}^2\]</span></p>
<ul>
<li><span class="math inline">\(l_j\)</span> = LD score of variant <span class="math inline">\(j\)</span></li>
<li>Measures amount of genetic variation <strong>tagged</strong> by variant <span class="math inline">\(j\)</span></li>
<li>SNPs in high-LD regions have high LD scores</li>
</ul>
<aside class="notes">
<p>The LD score is the number of “LD friends” — calculated as the sum of r² with all neighboring variants. Each genetic variant has one LD score.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polygenic-additive-model" class="slide level2">
<h2>Polygenic Additive Model</h2>
<p><span class="math display">\[Y = \sum_{k}^{M} X_k \cdot \beta_k + \epsilon \qquad \beta \sim N(0, \sigma_{\beta}^2)\]</span></p>
<ul>
<li>All <span class="math inline">\(M\)</span> common SNPs contribute to the phenotype</li>
<li>Effect sizes are drawn independently from a normal distribution</li>
<li>This is the main model for common disease genetics</li>
</ul>
<aside class="notes">
<p>Under this polygenic model, variants in high-LD regions are more likely to tag causal variants, so they will have higher chi-squared statistics on average. This is the key insight underlying LD score regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-distinguishes-confounding-from-polygenicity" class="slide level2">
<h2>LD Score Regression Distinguishes Confounding from Polygenicity</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1\]</span></p>
<ul>
<li><strong>Slope</strong> (<span class="math inline">\(Nh^2/M\)</span>): driven by true polygenicity → estimates <strong>heritability</strong></li>
<li><strong>Intercept</strong> (<span class="math inline">\(Na + 1\)</span>): driven by confounding → estimates <strong>population stratification / relatedness bias</strong></li>
</ul>
<aside class="notes">
<p>Bulik-Sullivan et al.&nbsp;show we can distinguish inflation due to confounding (flat line, intercept &gt; 1) from polygenicity (positive slope proportional to LD score). Variants in high-LD regions have higher chi-squared due to tagging more causal variants. Inflation from cryptic relatedness or population stratification from genetic drift does NOT correlate with LD score.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-parameters" class="slide level2">
<h2>LD Score Regression — Parameters</h2>

<img data-src="images/_page_32_Figure_1.jpeg" class="r-stretch"><table class="caption-top">
<colgroup>
<col style="width: 55%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(N\)</span></td>
<td>sample size</td>
</tr>
<tr class="even">
<td><span class="math inline">\(M\)</span></td>
<td>number of SNPs</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(h^2/M\)</span></td>
<td>variance explained per SNP</td>
</tr>
<tr class="even">
<td><span class="math inline">\(a\)</span></td>
<td>confounding: cryptic relatedness + population stratification</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(l_j = \sum_k r^2_{jk}\)</span></td>
<td>amount of genetic variation tagged by SNP <span class="math inline">\(j\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="ldsc-slope-vs.-intercept" class="slide level2">
<h2>LDSC: Slope vs.&nbsp;Intercept</h2>

<img data-src="images/_page_30_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>Confounding (population stratification, cryptic relatedness) produces a flat line with intercept &gt; 1 — inflation does not correlate with LD score. True polygenicity produces a positive slope — SNPs with more LD friends have higher chi-squared because they tag more causal variants.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-schizophrenia" class="slide level2">
<h2>LD Score Regression — Schizophrenia</h2>

<img data-src="images/_page_33_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>Schizophrenia has a very high LD score regression intercept, indicating substantial true polygenicity in addition to any confounding. The positive slope shows that SNPs with more LD friends have systematically higher chi-squared statistics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genomic-control-vs.-ld-score-regression" class="slide level2">
<h2>Genomic Control vs.&nbsp;LD Score Regression</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 32%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Trait</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (raw)</th>
<th><span class="math inline">\(\lambda_{GC}\)</span> (corrected)</th>
<th>LDSC intercept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ulcerative colitis</td>
<td>1.174</td>
<td>1.128</td>
<td>1.079 (0.010)</td>
</tr>
<tr class="even">
<td>Crohn’s disease</td>
<td>1.185</td>
<td>1.122</td>
<td>1.059 (0.008)</td>
</tr>
<tr class="odd">
<td>Schizophrenia</td>
<td>1.613</td>
<td>1.484</td>
<td>1.070 (0.010)</td>
</tr>
<tr class="even">
<td>ADHD</td>
<td>1.033</td>
<td>1.033</td>
<td>1.008 (0.006)</td>
</tr>
<tr class="odd">
<td>Bipolar disorder</td>
<td>1.154</td>
<td>1.135</td>
<td>1.030 (0.008)</td>
</tr>
<tr class="even">
<td>PGC cross-disorder</td>
<td>1.205</td>
<td>1.187</td>
<td>1.018 (0.008)</td>
</tr>
<tr class="odd">
<td>Major depression</td>
<td>1.063</td>
<td>1.063</td>
<td>1.009 (0.006)</td>
</tr>
<tr class="even">
<td>Rheumatoid arthritis</td>
<td>1.063</td>
<td>1.033</td>
<td>0.980 (0.007)</td>
</tr>
<tr class="odd">
<td>Coronary artery disease</td>
<td>1.125</td>
<td>1.096</td>
<td>1.033 (0.008)</td>
</tr>
<tr class="even">
<td>Type 2 diabetes</td>
<td>1.116</td>
<td>1.097</td>
<td>1.025 (0.008)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Notice that the LDSC intercept is systematically smaller than the genomic control λ. For schizophrenia, λ=1.613 looks alarming, but the LDSC intercept is only 1.070 — most of the inflation is true polygenicity, not confounding. Genomic control would have over-corrected.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-values-on-chromosome-22" class="slide level2">
<h2>LD Score Values on Chromosome 22</h2>

<img data-src="images/_L6_page_35_Figure_1.jpeg" class="r-stretch"><p>Calculated by Yanyu Liang using GTEx V8 reference variant set</p>
<aside class="notes">
<p>LD scores vary considerably across the chromosome, reflecting the local LD structure. Regions with high LD have high LD scores; sparse regions have low LD scores.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-between-traits" class="slide level2">
<h2>Genetic Correlation Between Traits</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><img data-src="images/_page_36_Figure_0.jpeg"></p>
</div><div class="column" style="font-size: 0.8em;">
<p>With the same assumptions, LD score regression can estimate <strong>genetic correlation</strong> between traits</p>
</div></div>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}}\]</span></p>
<aside class="notes">
<p>By regressing the product of Z-scores of two traits against LD scores, we can estimate their genetic correlation. This avoids confounders in observational studies and provides orthogonal evidence for associations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ld-score-regression-estimates-h²-and-genetic-correlation" class="slide level2">
<h2>LD Score Regression Estimates h² and Genetic Correlation</h2>
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{Nh^2}{M} l_j + Na + 1 \quad \leftarrow \text{ heritability + confounders}\]</span></p>
<p><span class="math display">\[E[z_{1j} z_{2j} \mid l_j] = \frac{\sqrt{N_1 N_2}}{M} \varrho_g \cdot l_j + \frac{\varrho N_s}{\sqrt{N_1 N_2}} \quad \leftarrow \text{ genetic correlation}\]</span></p>
<p>By partitioning LD scores into functional categories, we can also <strong>partition heritability by functional annotation</strong>.</p>
<aside class="notes">
<p>The same LD score regression framework extends to estimate: heritability, confounding bias, genetic correlation between traits, and partitioned heritability by functional category. This is a very powerful unified framework from a single GWAS run.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-cancers" class="slide level2">
<h2>Genetic Correlation Among Cancers</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Breast</th>
<th>Colorectal</th>
<th>Lung</th>
<th>Ovarian</th>
<th>Pancreatic</th>
<th>Prostate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Breast</td>
<td>1</td>
<td>0.22 (0.09)</td>
<td>0.27 (0.11)</td>
<td>0.26 (0.20)</td>
<td>0.17 (0.19)</td>
<td>0.06 (0.09)</td>
</tr>
<tr class="even">
<td>Colorectal</td>
<td>—</td>
<td>1</td>
<td>0.31 (0.10)</td>
<td>-0.08 (0.13)</td>
<td>0.55 (0.19)</td>
<td>0.09 (0.07)</td>
</tr>
<tr class="odd">
<td>Lung</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.17 (0.17)</td>
<td>0.32 (0.19)</td>
<td>0.095 (0.08)</td>
</tr>
<tr class="even">
<td>Ovarian</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.40 (0.29)</td>
<td>0.02 (0.14)</td>
</tr>
<tr class="odd">
<td>Pancreatic</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
<td>-0.06 (0.14)</td>
</tr>
<tr class="even">
<td>Prostate</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="source-credit">
<p><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5582139/">ncbi.nlm.nih.gov/pmc/articles/PMC5582139/</a></p>
</div>
</section>
<section id="genetic-correlation-cancer-and-other-diseases" class="slide level2">
<h2>Genetic Correlation: Cancer and Other Diseases</h2>

<img data-src="images/_page_39_Figure_1.jpeg" class="r-stretch"></section>
<section id="caveat-assortative-mating-confounds-genetic-correlation" class="slide level2">
<h2>Caveat: Assortative Mating Confounds Genetic Correlation</h2>
<p><strong>Cross-trait assortative mating</strong> inflates genetic correlation estimates</p>
<div class="source-credit">
<p>Border et al.&nbsp;<em>Cross-trait assortative mating is widespread and inflates genetic correlation estimates.</em> Science, 2022.</p>
</div>
<aside class="notes">
<p>If people mate non-randomly based on traits that are genetically correlated, this creates spurious genetic correlations. The Brainstorm Consortium and Border et al.&nbsp;show this is a real concern for psychiatric disorders.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="genetic-correlation-among-psychiatric-diseases" class="slide level2">
<h2>Genetic Correlation Among Psychiatric Diseases</h2>

<img data-src="images/_page_41_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Brainstorm Consortium. <em>Analysis of shared heritability in common disorders of the brain.</em> Science, 2018.</p>
</div>
<aside class="notes">
<p>The Brainstorm Consortium estimated genetic correlations among 25 brain disorders. Many psychiatric disorders show high genetic correlations with each other, suggesting shared biological mechanisms.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- ===== L8 original content starts here ===== -->
</section></section>
<section>
<section id="partitioning-heritability" class="title-slide slide level1 center">
<h1>Partitioning Heritability</h1>

</section>
<section id="partitioning-heritability-into-classes" class="slide level2">
<h2>Partitioning Heritability into Classes</h2>
<div class="formula">
<p><span class="math display">\[Y = \sum_{k \in \text{class 1}} \beta_k X_k + \sum_{k \in \text{class 2}} \beta_k X_k + \epsilon\]</span></p>
</div>
<div class="fragment">
<div class="formula">
<p><span class="math display">\[\text{Var}(Y) = \sigma^2_{\text{class1}} \cdot \text{GRM}_{\text{class1}} + \sigma^2_{\text{class2}} \cdot \text{GRM}_{\text{class2}} + \sigma^2_\epsilon\]</span></p>
</div>
<ul>
<li>GRM for each class built using only SNPs in that class</li>
<li>Variance components estimated by REML</li>
</ul>
<aside class="notes">
<p>We partition the genome into functional classes — e.g., coding regions, UTRs, enhancers — and ask how much heritability each class explains. The GRM is built separately for each class using only those SNPs, then REML estimates the variance components. The enrichment for a class is: (fraction of heritability in class) / (fraction of SNPs in class). A class with enrichment &gt; 1 carries more heritability per SNP than the genome average.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="partitioning-heritability-by-chromosome" class="slide level2">
<h2>Partitioning Heritability by Chromosome</h2>

<img data-src="images/_page_30_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Yang et al.&nbsp;<em>Genome partitioning of genetic variation for complex traits using common SNPs.</em> Nature Genetics, 2011.</p>
</div>
<aside class="notes">
<p>For height, heritability is roughly proportional to chromosome length — longer chromosomes carry more SNPs and explain more variance. This confirms that height is highly polygenic, with contributions spread across the whole genome. It also validates the method: if heritability were concentrated on one chromosome, we’d see a single outlier above the line.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="partitioning-heritability-by-chromosome-1" class="slide level2">
<h2>Partitioning Heritability by Chromosome</h2>

<img data-src="images/_page_31_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Yang et al.&nbsp;Nature Genetics, 2011.</p>
</div>
<aside class="notes">
<p>Some traits deviate from proportionality. Von Willebrand factor (vWF) shows enrichment on chromosome 12, where the VWF gene sits. QT interval shows chromosome-specific enrichment as well. These outliers highlight traits with major loci on specific chromosomes — consistent with what GWAS has found for those traits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!---
## Missing Heritability: Negligible with Imputed Variants

![](images/_page_32_Figure_0.jpeg)

::: {.source-credit}
Yang et al. *Genetic variance estimation with imputed variants finds negligible missing heritability for human height and BMI.* Nature Genetics, 2015.
:::

::: {.notes}
Earlier analyses using only genotyped SNPs explained less heritability than twin studies implied — the "missing heritability" problem. With dense imputation covering rare and low-frequency variants, nearly all the heritability for height and BMI is recovered. The gap was mostly due to incomplete tagging of causal variants, not biological mystery.
:::
--->
</section>
<section id="stratified-ld-score-regression" class="slide level2">
<h2>Stratified LD Score Regression</h2>
<div class="formula">
<p><span class="math display">\[E[\chi^2 \mid l_j] = \frac{N h^2 l_j}{M} + Na + 1\]</span></p>
</div>
<div class="fragment">
<div class="formula">
<p><span class="math display">\[E\!\left[\chi_j^2\right] = N \sum_C \tau_C \,\ell(j,C) + Na + 1\]</span></p>
</div>
<ul>
<li><span class="math inline">\(\ell(j,C)\)</span>: LD score of SNP <span class="math inline">\(j\)</span> restricted to annotation category <span class="math inline">\(C\)</span></li>
<li><span class="math inline">\(\tau_C\)</span>: per-SNP heritability contribution from category <span class="math inline">\(C\)</span></li>
<li><strong>Enrichment</strong> = (fraction of heritability) / (fraction of SNPs)</li>
</ul>
<aside class="notes">
<p>This extends the basic LDSC model (from L6) to annotation categories. If SNPs in a functional category carry more heritability per SNP than the genome average, they produce inflated chi-squared statistics relative to their annotation-specific LD scores. Regressing chi-squared on the annotation LD scores gives tau_C for each category. Runs on summary statistics alone — no individual-level data required.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="how-do-you-calculate-χ²-from-gwas-summary-statistics" class="slide level2">
<h2>How Do You Calculate χ² from GWAS Summary Statistics?</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>CHR</th>
<th>SNP</th>
<th>A1</th>
<th>BETA</th>
<th>STAT</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>22</td>
<td>rs11089128</td>
<td>G</td>
<td>−3593</td>
<td>−2.09</td>
<td>0.037</td>
</tr>
<tr class="even">
<td>22</td>
<td>rs7288972</td>
<td>C</td>
<td>−3333</td>
<td>−2.392</td>
<td>0.017</td>
</tr>
<tr class="odd">
<td>22</td>
<td>rs11167319</td>
<td>G</td>
<td>−229.6</td>
<td>−0.154</td>
<td>0.878</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><span class="math display">\[\chi^2 = \text{STAT}^2\]</span></p>
<p>Most GWAS output files report a <strong>Z-score</strong> (or t-statistic) in the STAT column. Squaring it gives χ².</p>
<aside class="notes">
<p>Under the null of no association, the squared Wald statistic follows a chi-squared distribution with 1 degree of freedom. Note that beta alone doesn’t give you chi-squared — you also need the standard error (or the test statistic directly). LD score regression uses chi-squared, so this conversion is the first step when running S-LDSC on GWAS summary stats.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="stratified-ld-score-regression-enrichment" class="slide level2">
<h2>Stratified LD Score Regression — Enrichment</h2>

<img data-src="images/_page_35_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>Finucane et al.&nbsp;<em>Partitioning heritability by functional annotation using genome-wide association summary statistics.</em> Nature Genetics, 2015.</p>
</div>
<aside class="notes">
<p>Heritability enrichment across 24 functional annotations for various traits. DNase I hypersensitive sites, conserved regions, and coding regions show the strongest enrichment — far more heritability per SNP than their genome fraction. This motivates looking at eQTLs: if heritability is enriched in regulatory regions, then variants that regulate gene expression are likely driving GWAS signals.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="gene-expression-traits-functional-annotation-enrichment" class="slide level2">
<h2>Gene Expression Traits: Functional Annotation Enrichment</h2>

<img data-src="images/_page_36_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>Applying the same stratified LDSC to eQTL summary statistics (gene expression as phenotype) shows enrichment in the same regulatory categories. The genetic architecture of gene expression is concentrated in functional elements — binding sites, open chromatin, conserved regions. eQTLs are not random across the genome; they cluster in regulatory regions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="enrichment-of-tissue-types" class="slide level2">
<h2>Enrichment of Tissue Types</h2>

<img data-src="images/_page_37_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>We can also partition by tissue-specific annotations — liver-specific enhancers, brain-specific open chromatin, etc. The enrichment pattern for a given GWAS trait reveals which tissues are most relevant: liver annotations are enriched for LDL cholesterol, brain annotations for psychiatric traits. This implicates tissues without requiring direct functional experiments.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!---
## The Perils of Polygenicity

![](images/_page_38_Picture_1.jpeg)

::: {.source-credit}
Modified from [D. Posthuma, Twitter, 2020](https://twitter.com/DPosthu/status/1328662943739867137)
:::

::: {.notes}
A cautionary note. Because complex traits are influenced by thousands of variants — many in LD with each other — we can end up with an overwhelming number of "associated" loci. Fine-mapping helps narrow these down to credible sets, and enrichment analysis helps prioritize tissues and annotations. But the fundamental challenge is that polygenicity makes individual variant interpretation hard. We are moving from single-variant thinking to pathway- and tissue-level inference.
:::
--->
</section></section>
<section>
<section id="from-gwas-to-mechanisms" class="title-slide slide level1 center">
<h1>From GWAS to Mechanisms</h1>

</section>
<section id="gwas-variants-are-mostly-non-coding" class="slide level2">
<h2>GWAS Variants Are Mostly Non-Coding</h2>

<img data-src="images/_page_1_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>GWAS Catalog</p>
</div>
<aside class="notes">
<p>The GWAS catalog has accumulated thousands of associations. The vast majority of associated variants fall in non-coding regions — introns, intergenic regions, regulatory elements. They are unlikely to change protein function directly. The question is: how do these non-coding variants influence phenotype?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="non-coding-variants-act-through-gene-regulation" class="slide level2">
<h2>Non-Coding Variants Act Through Gene Regulation</h2>

<img data-src="images/_page_2_Picture_0.jpeg" class="r-stretch"><aside class="notes">
<p>Most GWAS variants are in non-coding regions. The emerging consensus is that they affect complex traits by regulating total mRNA levels (gene expression) and pre-mRNA splicing — not by changing the protein sequence itself.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="altered-protein-levels-influence-disease-risk" class="slide level2">
<h2>Altered Protein Levels Influence Disease Risk</h2>

<img data-src="images/albert-kruglyak-2015-eQTL-pQTL.png" class="r-stretch"><div class="source-credit">
<p>Albert &amp; Kruglyak. <em>The role of regulatory variation in complex traits and disease.</em> Nature Reviews Genetics, 2015.</p>
</div>
<aside class="notes">
<p>This cartoon shows the mechanism: the blue-star allele allows a TF to bind, driving high expression of gene X → high protein → increased disease risk. The yellow allele blocks TF binding → lower expression → lower risk. The variant doesn’t change the protein sequence — it changes how much protein is made. This is the paradigm that motivates studying eQTLs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="total-mrna-and-splicing-affect-complex-traits" class="slide level2">
<h2>Total mRNA and Splicing Affect Complex Traits</h2>

<img data-src="images/li-2016-regulatory-mechanisms.png" class="r-stretch"><div class="source-credit">
<p>Li et al.&nbsp;<em>RNA splicing is a primary link between genetic variation and disease.</em> Science, 2016.</p>
</div>
<aside class="notes">
<p>Beyond total expression, alternative splicing is a second regulatory layer. sQTLs (splicing QTLs) are variants that alter the ratio of alternatively spliced isoforms. Both eQTLs and sQTLs are candidate mechanisms for how non-coding GWAS variants act on phenotype.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-gtex-project" class="slide level2">
<h2>The GTEx Project</h2>

<img data-src="images/_page_8_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>The GTEx Consortium. <em>The GTEx Consortium atlas of genetic regulatory effects across human tissues.</em> Science, 2020.</p>
</div>
<aside class="notes">
<p>GTEx was established in 2010 to map genetic regulatory effects across human tissues at scale. The v8 study collected 17,382 tissue samples from 838 donors across 54 tissues, all with RNA-seq and 30x WGS. 49 tissues had 73–706 samples for QTL mapping. The logistical effort — donor consent from families, tissue collection, preservation, sequencing, QC — was enormous.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="gtex-v8-scale-and-design" class="slide level2">
<h2>GTEx v8: Scale and Design</h2>
<ul>
<li>Established <strong>2010</strong> to map genetic regulatory effects across human tissues</li>
<li><strong>17,382</strong> tissue samples from <strong>838</strong> donors across <strong>54</strong> tissues</li>
<li>All samples: RNA-seq + 30x whole genome sequencing</li>
<li><strong>49</strong> tissues with 73–706 samples used for QTL mapping</li>
</ul>
<aside class="notes">
<p>The scale of GTEx v8 is what makes it powerful: near-complete tissue coverage, large per-tissue sample sizes, and matched WGS enabling precise genotyping. The logistical effort — donor consent from families, tissue collection, preservation, sequencing, QC — was enormous.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="expression-quantitative-trait-loci-eqtls" class="slide level2">
<h2>Expression Quantitative Trait Loci (eQTLs)</h2>

<img data-src="images/_page_9_Figure_1.jpeg" class="r-stretch"><div class="source-credit">
<p>GTEx Portal — <a href="https://gtexportal.org/home/locusBrowserPage/ACTN3">gtexportal.org</a></p>
</div>
<aside class="notes">
<p>An eQTL is a genetic variant associated with the mRNA level of a gene. This example shows ACTN3 expression in tibial artery: individuals with different genotypes at a nearby variant have clearly different expression levels. The GTEx portal lets you look up any gene and see its eQTLs across tissues interactively — a useful resource for interpreting GWAS hits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="egenes-scale-with-sample-size" class="slide level2">
<h2>eGenes Scale with Sample Size</h2>

<img data-src="images/_page_10_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>The GTEx Consortium. Science, 2020.</p>
</div>
<aside class="notes">
<p>eGenes are genes with at least one significant cis-eQTL. Each point is a tissue; x-axis is sample size. The trend is clear: more samples → more eGenes. The curve hasn’t flattened, suggesting most expressed genes will eventually have a detectable eQTL. sGenes (splicing QTLs) follow a similar trend but need larger sample sizes — splicing is a subtler signal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="qtl-discovery-across-tissues" class="slide level2">
<h2>QTL Discovery Across Tissues</h2>

<img data-src="images/_page_11_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>The GTEx Consortium. Science, 2020.</p>
</div>
<aside class="notes">
<p>GTEx v8 found cis-eQTLs for the majority of expressed genes across tissues. Panel B shows allelic heterogeneity: many eGenes have multiple independent eQTLs. Panel D shows a sex-biased eQTL for AURKA in skeletal muscle — strong effect in males, absent in females. Panel E shows a population-biased eQTL with different effect sizes in African Americans vs.&nbsp;European Americans. These context-dependent effects matter for GWAS interpretation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="regulatory-mechanisms-of-gwas-loci" class="slide level2">
<h2>Regulatory Mechanisms of GWAS Loci</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><img data-src="images/eqtl-more-likely-gwas-pgen.1000888.g001.png"></p>
</div><div class="column" style="width:40%;">
<p>Trait-Associated SNPs Are More Likely to Be eQTLs: Annotation to Enhance Discovery from GWAS</p>
</div></div>
<div class="source-credit">
<p>Nicolae et al.&nbsp;<em>Trait-Associated SNPs Are More Likely to Be eQTLs: Annotation to Enhance Discovery from GWAS.</em> PLoS Genetics, 2010.</p>
</div>
<aside class="notes">
<p>Trait-associated SNPs from GWAS are significantly more likely to be eQTLs than random SNPs, across multiple traits and tissues. This provides strong evidence that regulatory variation — variants affecting gene expression — is a primary mechanism through which GWAS loci influence complex traits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="functional-genomic-regions-are-enriched-among-eqtls-and-sqtls" class="slide level2">
<h2>Functional Genomic Regions Are Enriched Among eQTLs and sQTLs</h2>

<img data-src="images/_page_22_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>The GTEx Consortium. Science, 2020.</p>
</div>
<aside class="notes">
<p>cis-eQTLs are enriched in functional annotations: UTRs, splice sites, TF binding sites. Many trans-eQTLs are mediated through cis-eQTLs: a cis variant changes expression of a regulatory gene, which in turn affects other genes in trans. Panels D-E show cis-mediating genes with multiple trans-eQTLs — these are likely regulatory hubs whose expression levels propagate effects broadly across the transcriptome.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="fine-mapping" class="title-slide slide level1 center">
<h1>Fine-Mapping</h1>

</section>
<section id="fine-mapping-the-problem" class="slide level2">
<h2>Fine-Mapping: The Problem</h2>

<img data-src="images/_page_15_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>A typical GWAS regional plot: many SNPs are statistically associated because they are in LD with the causal variant. The causal variant is not obvious. Fine-mapping methods try to identify the most likely causal variant(s) within such a region. This requires association results for all variants in the locus — either from dense genotyping or imputation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fine-mapping-the-goal" class="slide level2">
<h2>Fine-Mapping: The Goal</h2>
<ul>
<li><strong>Fine-mapping:</strong> identify the causal variant underlying an observed association</li>
<li>Many variants in LD tag the true signal — the causal one is not obvious</li>
<li>Requires results for <strong>all</strong> variants in the locus (imputation or dense genotyping)</li>
<li>Build <strong>credible sets</strong>: sets of SNPs 95% likely to contain the causal variant</li>
<li>Assign <strong>Posterior Inclusion Probability (PIP)</strong> to each variant</li>
</ul>
<aside class="notes">
<p>Credible sets are the Bayesian analog of a confidence interval, but for the identity of the causal variant. A 95% credible set is the smallest set of SNPs such that there is 95% posterior probability at least one is causal. PIP is the probability a specific variant is causal. High-PIP variants are strong candidates for functional follow-up or annotation overlap.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fine-mapping-susie-example" class="slide level2">
<h2>Fine-Mapping: SuSiE Example</h2>

<img data-src="images/_page_17_Figure_0.jpeg" class="r-stretch"><aside class="notes">
<p>SuSiE (Sum of Single Effects) is now the most widely used fine-mapping method. This figure illustrates a challenging case: the strongest marginal association is NOT the causal variant. Despite this, SuSiE converges to two credible sets, each containing a true causal variant. The method handles multiple causal variants per locus and avoids being misled by strong non-causal associations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fine-mapping-ibss-algorithm" class="slide level2">
<h2>Fine-Mapping: IBSS Algorithm</h2>

<img data-src="images/_page_18_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>Wang et al.&nbsp;<em>A simple new approach to variable selection in regression, with application to genetic fine mapping.</em> JRSS-B, 2020.</p>
</div>
<aside class="notes">
<p>The IBSS (Iterative Bayesian Stepwise Selection) algorithm is the engine behind SuSiE. After one iteration it incorrectly includes the strongest marginal association in a credible set. After 10 iterations (at convergence) it has corrected itself: two credible sets each containing a true causal variant, neither containing the SMA. One credible set has just 3 SNPs (purity 0.85); the other has 37 highly correlated variants (purity 0.97) — small individual PIPs but high confidence that one is causal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fine-mapping-methods" class="slide level2">
<h2>Fine-Mapping Methods</h2>
<ul>
<li><strong>CAVIAR</strong> (Hormozdiari et al., Bioinformatics 2015)</li>
<li><strong>FINEMAP</strong> (Benner et al., Bioinformatics 2016)</li>
<li><strong>fastPAINTOR</strong> (Kichaev et al., Bioinformatics 2016)</li>
<li><strong>DAP-G</strong> (Wen et al., AJHG 2016)</li>
<li><strong>SuSiE</strong> (Wang et al., JRSS-B 2020) — current standard</li>
</ul>
<aside class="notes">
<p>All methods take summary statistics plus an LD reference panel as input; some also accept individual-level data. SuSiE has become standard due to computational efficiency and the ability to model multiple causal variants per locus. Fine-mapping output can be combined with ENCODE or other functional annotations to further prioritize variants within credible sets.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fine-mapping-of-cis-eqtls-in-gtex" class="slide level2">
<h2>Fine-Mapping of cis-eQTLs in GTEx</h2>

<img data-src="images/_page_20_Figure_0.jpeg" class="r-stretch"><div class="source-credit">
<p>The GTEx Consortium. Science, 2020.</p>
</div>
<aside class="notes">
<p>GTEx applied fine-mapping to cis-eQTLs across all tissues. Panel A: the number of eGenes with a high-confidence fine-mapped variant (PIP &gt; 0.5) increases with sample size, but flattens for small-effect eQTLs — harder to fine-map. Panel B: fine-mapped variants are more enriched in validated regulatory elements than the top eVariant alone. Panel C: for CBX8, the credible set overlaps EGR1 binding sites — the variant disrupts the EGR1 motif, directly implicating TF binding as the mechanism.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="encode" class="title-slide slide level1 center">
<h1>ENCODE</h1>

</section>
<section id="encode-encyclopedia-of-dna-elements" class="slide level2">
<h2>ENCODE: Encyclopedia of DNA Elements</h2>
<ul>
<li>Pilot phase launched in 2003</li>
<li>Goal: catalog all <strong>functional elements</strong> in the human genome
<ul>
<li>Elements acting at the protein and RNA level</li>
<li>Regulatory elements controlling when and where genes are active</li>
</ul></li>
<li>Characterizes functional elements of the genome and epigenome</li>
</ul>
<aside class="notes">
<p>ENCODE is the large-scale consortium that produced the regulatory annotation data used by stratified LDSC, fine-mapping tools, and colocalization methods. It provides information on open chromatin (DNase-seq, ATAC-seq), TF binding (ChIP-seq), histone modifications, and more — across hundreds of cell types. Crucially, ENCODE provides region-level information, not variant-level: it tells you a position is in a regulatory region, not which allele is functional.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="encode-regulatory-annotations" class="slide level2">
<h2>ENCODE Regulatory Annotations</h2>

<img data-src="images/_page_27_Figure_1.jpeg" class="r-stretch"><aside class="notes">
<p>ENCODE annotations define regions with evidence for regulatory activity: open chromatin, TF binding sites, promoters, enhancers. These are the categories used in stratified LDSC enrichment analysis. The key limitation: ENCODE tells you the region is regulatory, but not which variant in the region is causal. Fine-mapping narrows the credible set; ENCODE and other functional data help prioritize within it. Together these tools move us from a GWAS p-value to a specific variant in a specific regulatory context.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="L8-eQTL-finemapping-enrichment_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>